### ISSUE TITLE
Пересечение рецептов бетона и красителя

### ISSUE THREAD

**Issue by FireWarrior2** [GT-IMPACT/IMPACT-1#10]
Какую версию модпака вы используете?
1.0 rc

Вы играете в одиночке или на сервере?
одиночка

Опишите ошибку (Если нужно, приложите скриншоты)
Пересечение рецептов: из кальцита без микросхемы делается краситель, а с ней - бетон. 
![2020-09-12_11 25 21](https://user-images.githubusercontent.com/18097458/92993466-762ec780-f4fa-11ea-8630-fb108e305118.png)
![2020-09-12_11 25 49](https://user-images.githubusercontent.com/18097458/92993468-76c75e00-f4fa-11ea-873e-41a534e2778a.png)

Какие изменения вы предлагаете?
Добавить микросхему к рецептам производства красителей

**Comment by Spartak1997** [comment]
Done

**Comment by FireWarrior2** [comment]
тест

**Comment by FireWarrior2** [comment]
1.0 rc2
одиночка
Даже со 2 микрухой рецепты пересекаются
![2020-11-13_01 06 23](https://user-images.githubusercontent.com/18097458/99002248-306b9b00-254d-11eb-81f1-a67db0d032e2.png)
![2020-11-13_01 06 59](https://user-images.githubusercontent.com/18097458/99002251-319cc800-254d-11eb-8d04-c82ff0273fcc.png)
