### ISSUE TITLE
Coke Oven Brick

### ISSUE THREAD

**Issue by Zebrix** [GT-IMPACT/IMPACT-1#103]
Какую версию модпака вы используете?
1.0.0.1

Вы играете в одиночке или на сервере?
Сервер

Опишите ошибку (Если нужно, приложите скриншоты)
Не стакаются блоки коковины - новые/юзаные.
P.S. Крафтил и ставил в 1.0.0.1 версии, а не старинные снимал.

Какие изменения вы предлагаете?
Fix.

**Comment by Spartak1997** [comment]
Это связано с тем, что до обновления 1.0.0.0 рецепты кирпичей сохраняли нбт, однако этот косяк уже исправлен, так что если вы попробуете заново собрать их, то будет все нормально, вне зависимости от "формы" крафта.

**Comment by Zebrix** [comment]
Так я же написал, что стартовал новый мир в 1.0.0.1, где собственно их и крафтил.
