### ISSUE TITLE
Крафт Graphene Dust

### ISSUE THREAD

**Issue by mihaillatyshov** [GT-IMPACT/IMPACT-1#104]
Какую версию модпака вы используете?
IMPACT 1.0.0.1

Вы играете в одиночке или на сервере?
Сервер

Опишите ошибку (Если нужно, приложите скриншоты)
Очень странное количество Graphene, получается одна пылька из 24 других пылек
![2020-12-21_04 28 52](https://user-images.githubusercontent.com/35631710/102730475-fb214c80-4345-11eb-8308-ef023c34efc1.png)

Какие изменения вы предлагаете?
Изменить получаемое количество (не похоже на правильно прописанный рецепт)

**Comment by Spartak1997** [comment]
Все здесь верно.
