### ISSUE TITLE
Pollucite

### ISSUE THREAD

**Issue by RaitGamerGR** [GT-IMPACT/IMPACT-1#106]
**Какую версию модпака вы используете?**
Новейшую! Сегодняшнюю!

**Вы играете в одиночке или на сервере?**
Сервер ZonaSumraka

**Опишите ошибку (Если нужно, приложите скриншоты)**
Centrifuged Pollucite при дроблении не имеет побочного продукта. Так же мытая руда Pollucite в Industrial Pulverizer не даёт побочку от дробления.

**Какие изменения вы предлагаете?**
Добавить побочный продукт при обработке

**Comment by aagrishankov** [comment]
Будет включено в рефакторинг рудогена
