### ISSUE TITLE
Ошибки в названиях новых генераторов

### ISSUE THREAD

**Issue by FireWarrior2** [GT-IMPACT/IMPACT-1#11]
Какую версию модпака вы используете?
1.0 rc2

Вы играете в одиночке или на сервере?
одиночка

Опишите ошибку (Если нужно, приложите скриншоты)
Ошибки в названии наквадаховых генераторов - Genrator
![2020-09-19_20 42 17](https://user-images.githubusercontent.com/18097458/93685573-ed46fb80-fab8-11ea-82e8-25e8fa5d9d80.png)
![2020-09-19_20 42 20](https://user-images.githubusercontent.com/18097458/93685574-ee782880-fab8-11ea-81da-77c455647643.png)

Какие изменения вы предлагаете?
Generator[](url)

**Comment by aagrishankov** [comment]
https://github.com/GT-IMPACT/Impact-Core/pull/8
