### ISSUE TITLE
Приземление на Европу

### ISSUE THREAD

**Issue by FireWarrior2** [GT-IMPACT/IMPACT-1#111]
Какую версию модпака вы используете?
1.0.0.2

Вы играете в одиночке или на сервере?
одиночка

Опишите ошибку (Если нужно, приложите скриншоты)
Не выдает площадку в посадочном модуле после посадки на Европу, только ракету.
![2020-12-23_00 35 51](https://user-images.githubusercontent.com/18097458/102936890-144b0a00-44ba-11eb-89e5-d3e934bd1e85.png)

Какие изменения вы предлагаете?
Должно выдавать

**Comment by aagrishankov** [comment]
Потестил у себя, из  10 раз полетов, выдавал каждый раз, попробуй еще раз у себя

**Comment by aagrishankov** [comment]
еще пару полетов сделал специально, не могу воспроизвести баг, ишую закрою пока, если найду сам баг этот - пофикшу
