### ISSUE TITLE
Поверхностный лед

### ISSUE THREAD

**Issue by FireWarrior2** [GT-IMPACT/IMPACT-1#112]
Опишите ваше предложение
На некоторых планетах встречается Поверхностный лед. Предлагаю добавить ему переработку.
![2020-12-23_01 01 19](https://user-images.githubusercontent.com/18097458/102937158-93d8d900-44ba-11eb-9acc-1230fb41e4f5.png)

Какие проблемы решит/добавит ваше предложение?
?

Объясните, почему ваше предложение должны реализовать?
Большинство породы с планет имеют переработку, почему бы ее и льду не добавить..

**Comment by LewisSaber** [comment]
На какой планете впервые встречается? Штоб знать под какой тир ставить обработку

**Comment by FireWarrior2** [comment]
Я встретил на Ганимеде (3)
