### ISSUE TITLE
Приземление на спутники Марса

### ISSUE THREAD

**Issue by FireWarrior2** [GT-IMPACT/IMPACT-1#113]
Опишите ваше предложение
При приземлении на все планеты видно "планету" снизу. Фобос и Деймос не видно
![2020-12-23_00 29 01](https://user-images.githubusercontent.com/18097458/102938032-86245300-44bc-11eb-9c30-61c0bd752564.png)
![2020-12-23_01 15 26](https://user-images.githubusercontent.com/18097458/102938033-86bce980-44bc-11eb-8e58-1cf95f55ed4a.png)

Какие проблемы решит/добавит ваше предложение?
?

Объясните, почему ваше предложение должны реализовать?
Для порядка

**Comment by aagrishankov** [comment]
чет посмотрел, там надо рендер весь переписывать, а у меня исходников нету, думаю не критично что нету их, ишую закрою
