### ISSUE TITLE
Отображение режимов у бура

### ISSUE THREAD

**Issue by RaitGamerGR** [GT-IMPACT/IMPACT-1#119]
**Опишите ваше предложение**
Добавить отображение режима бура на его текстурке
(подпись в углу, светодиодик разноцветный) что б видеть режим бура не переключая и не заходя в инвентарь для проверки тултипа.

**Какие проблемы решит/добавит ваше предложение?**
Решит проблему случайного вскапывания базы

**Объясните, почему ваше предложение должны реализовать?**
Потому что уже много человеков случайно сносило много лишнего

**Comment by LewisSaber** [comment]
А не проще ли зделать себе лв бур для работы на базе? Хотя ето добавить стоит тоже

**Comment by RaitGamerGR** [comment]
Не проще. Под каждый режим свой бур таскать?
Я бур использую не только в одном режиме. Иногда надо сломать 1х1, иногда 5х5.

**Comment by aagrishankov** [comment]
https://github.com/GT-IMPACT/GT5.09OFFBEAT/commit/8e2741dc10810bb4d74a0a77f20bd5e9f76f4b60
