### ISSUE TITLE
Неправильный рецепт кинетического генератора из IC2

### ISSUE THREAD

**Issue by FireWarrior2** [GT-IMPACT/IMPACT-1#12]
Какую версию модпака вы используете?
1.0 rc 2

Вы играете в одиночке или на сервере?
одиночка

Опишите ошибку (Если нужно, приложите скриншоты)
Неправильный рецепт кинетического генератора из IC2 - вольфрамовый кабель на 8кВ.
![2020-09-19_21 03 50](https://user-images.githubusercontent.com/18097458/93686034-3d738d00-fabc-11ea-8a0b-31e34e0bf363.png)

Какие изменения вы предлагаете?
Заменить на алюминиевый кабель (2кВ), так как вольфрамовый используется для следующего тира генератора.

**Comment by aagrishankov** [comment]
https://github.com/GT-IMPACT/Impact-Core/commit/d62f9dacbb55320ed70c72eb96f87efc6ea65dde
