### ISSUE TITLE
Копать?

### ISSUE THREAD

**Issue by Zebrix** [GT-IMPACT/IMPACT-1#124]
Опишите ваше предложение
В 1.12 у тинкера есть интересный вариант модификатора - global traveler. Который всё накопанное засовывает в привязанный к инструменту сундук/инвентарь. И только при заполнении уже как обычный бросает на пол при копании.
Так вот у нас есть крутые дрели, которые накапывают больше чем можно унести, а АЕшный магнит говорят лагуч. Не будет ли сложной реализация чего то подобного? Пусть не шибко читерно, требуя специального "приемника", но если можно убрать вероятные лаги при копании, было бы весьма полезным.

Какие проблемы решит/добавит ваше предложение?
Минус полный инвентарь сумок.

Объясните, почему ваше предложение должны реализовать?

Ну это уже по желанию, просто небольшая идея.

**Comment by Spartak1997** [comment]
Такая механика есть у EnderStorage, т.е. линкуешь рюкзак к сундуку соответсвующим цветом и благодаря этому весь шмот спокойно тпхается на базу.

**Comment by Zebrix** [comment]
Ну там всё же читерная штука в плане допустимой автоматизации с передачей между измерениями. А это чисто однонаправленный ручной инструмент.
