### ISSUE TITLE
draconic evolution

### ISSUE THREAD

**Issue by DiFaYaL** [GT-IMPACT/IMPACT-1#126]
Опишите ваше предложение
Добавить возможность вешать предметы на другой блок.
![Screenshot_3](https://user-images.githubusercontent.com/28961321/103172863-3ac4c880-485f-11eb-87fb-510f17b2cd5d.png)

Какие проблемы решит/добавит ваше предложение?
Все проблемы мира майнкрафта

Объясните, почему ваше предложение должны реализовать?
Удобно

**Comment by LewisSaber** [comment]
закрывай @DiFaYaL #110
