### ISSUE TITLE
Европа

### ISSUE THREAD

**Issue by FireWarrior2** [GT-IMPACT/IMPACT-1#127]
Опишите ваше предложение
Предлагаю убрать породу Европы из рецепта ракеты 4 тира или что-то сделать со структурой планеты.

Какие проблемы решит/добавит ваше предложение?
Не придется выкапывать неадекватно большую площадь для получения 16 тыс. породы на данной планеты.

Объясните, почему ваше предложение должны реализовать?
У Европы в новых версиях весьма специфичная структура, и нужная порода находится в тонких слоях сверху и у коренной породы. Поэтому, чтобы выкопать 16 тыс. породы для ракеты, нужно обработать (например, карьерами) неадекватно большую территорию по сравнению с другими планетами т3.
![2020-12-27_17 50 14](https://user-images.githubusercontent.com/18097458/103173863-bda14f80-486e-11eb-8607-ed247ec9cc10.png)

**Comment by aagrishankov** [comment]
Так как понижено количество породы для схем, теперь копать реально
