### ISSUE TITLE
Жидкие интерфейсы 

### ISSUE THREAD

**Issue by kirilwapj** [GT-IMPACT/IMPACT-1#128]
Какую версию модпака вы используете?
1.0.0.2

Вы играете в одиночке или на сервере?
Одиночка

Опишите ошибку (Если нужно, приложите скриншоты)

Если заказать крафт который стоит в жидком интерфейсе но для крафта не хватает требуемой жидкости то после появления данной жидкости в системе интерфейс не доливает эту жидкость потребителю.

Какие изменения вы предлагаете?
Исправить эту ошибку если возможно.

**Comment by aagrishankov** [comment]
Работа над интерфейсами из мода ExtraCells больше не будет проводится. Данные устройства внесены в список нежелательных для использования. Из сборки удалены не будут. Использование данных устройств на ваш страх и риск

**Comment by kirilwapj** [comment]
> Работа над интерфейсами из мода ExtraCells больше не будет проводится. Данные устройства внесены в список нежелательных для использования. Из сборки удалены не будут. Использование данных устройств на ваш страх и риск

А какие ещё есть варианты автоматизации крафтов с жидкостями?

**Comment by LewisSaber** [comment]
связка fluid extractor + мех либо волумерики
