### ISSUE TITLE
Забыли удалить злых мобов на планетах

### ISSUE THREAD

**Issue by FireWarrior2** [GT-IMPACT/IMPACT-1#13]
Какую версию модпака вы используете?
1.0 rc 2

Вы играете в одиночке или на сервере?
одиночка

Опишите ошибку (Если нужно, приложите скриншоты)
Забыли удалить злых мобов на планетах.
![2020-09-19_21 23 05](https://user-images.githubusercontent.com/18097458/93686369-701e8500-fabe-11ea-8926-89ac1764eb0d.png)

Какие изменения вы предлагаете?
Удалить и их

**Comment by aagrishankov** [comment]
Баг конечно интересный, но и занимательный, потому что у меня не было мобов в космосе, я их проверял))
Ладно посмотрим что могло пойти не так

**Comment by aagrishankov** [comment]
https://github.com/GT-IMPACT/Impact-Core/commit/0d2a180116958c5f5984e809dd479c803d78baf7
