### ISSUE TITLE
Плутоний-241 для ТЯР т1

### ISSUE THREAD

**Issue by FireWarrior2** [GT-IMPACT/IMPACT-1#130]
Опишите ваше предложение
Альтернативы:
1) Уменьшить количество плутония в рецепте до одной двойной-тройной пластины. Сложнее, чем в ванильном, но адекватно
2) Добавить в переработку пыли с т4 планет 239 плутоний с хорошим шансом (1/4 пыли с 25% шансом условно)
3) Добавить мелкую плутониевую-239 руду на эти планеты
4) Увеличить выход плутония с мох (например, с одного четверного стержня 4 плутония за 10000 с)
5) С наквадах-химии имеется довольно имбовый по сравнению с перечисленными выше способами получения плутония-241 рецепт из наквадрии. Предлагаю поднять напряжение ему.
6) Можно вообще заменить плутоний-241 на лув материал. Например, наквадаховый сплав.

Какие проблемы решит/добавит ваше предложение?
Исправит неадекватно большое время ожидания 241 плутония для ТЯР т1.

Объясните, почему ваше предложение должны реализовать?
Сейчас на ив-лув для 36 плутония-241 нужно неадекватно много времени и ресурсов.
Например, ЯР на мох. 5 четверных стержней за 10000 с произведут всего 20 самородков 239-плутония, которого нужно около 1600 слитков.
Если получать из породы Фобоса, то нужно переработать около 900 тыс. породы

**Comment by aagrishankov** [comment]
так как появился реактор, потребность в этом отпала)
