### ISSUE TITLE
Laptop при использовании на МЕ компонентах приводит к дисконекту от сервера

### ISSUE THREAD

**Issue by Donny-zs** [GT-IMPACT/IMPACT-1#133]
Какую версию модпака вы используете?
1.0.0.2

Вы играете в одиночке или на сервере?
сервер ZonaSumraka

Опишите ошибку (Если нужно, приложите скриншоты)
При использовании Laptop на ме компоненты происходит краш клиента, с вылетом в главное меню, ошибка - internal server error

**Comment by FireWarrior2** [comment]
В одиночке краш.
