### ISSUE TITLE
Т5 ракета, IV солнечная панель и драконий

### ISSUE THREAD

**Issue by FireWarrior2** [GT-IMPACT/IMPACT-1#134]
Опишите ваше предложение
Предлагаю заменить драконий/мейтнерий в головном обтекателе ракеты т5 на другой ЗПМ материал, например, наквадаховый сплав.
Если IV солярка предполагается на LuV, то драконий в рецепте Irradiant reinforced chrome plate так же стоит заменить.
![2021-01-01_13 51 29](https://user-images.githubusercontent.com/18097458/103437636-d5941d00-4c3a-11eb-9ca9-fdcaba2dd87a.png)

Какие проблемы решит/добавит ваше предложение?
?

Объясните, почему ваше предложение должны реализовать?
Сейчас для создания т5 ракеты нужно сделать т1 фузионку, а затем т2, для дракония. Логичнее будет, если фузионка т2 будет нужна уже только для т6 ракеты.

**Comment by Spartak1997** [comment]
Пока изменил рецепт у ракеты. Насчет солярки надо еще подумать
