### ISSUE TITLE
Очки или шлем?

### ISSUE THREAD

**Issue by RaitGamerGR** [GT-IMPACT/IMPACT-1#136]
**Опишите ваше предложение**
Добавить возможность носить очки опенкомпутерса(AR Glasses) в слоте маски тинкерса

**Какие проблемы решит/добавит ваше предложение?**
Решит очень важный философский вопрос, носить очки или шлем.

**Объясните, почему ваше предложение должны реализовать?**
Потому что очки и шлем разом!

**Comment by aagrishankov** [comment]
Добавил мод Baubles и подружил очки
