### ISSUE TITLE
Четырех и девяти жидкостных хэчах не загружается жидкость

### ISSUE THREAD

**Issue by kirilwapj** [GT-IMPACT/IMPACT-1#138]
Какую версию модпака вы используете?
1.0.0.2

Вы играете в одиночке или на сервере?
1

Опишите ошибку (Если нужно, приложите скриншоты)
После крафта в хэче остается старая жидкость с надписью 0 / 16000 при этом жидкость другого типа не заливается. 
см. скрин.

![2021-01-03_22 27 21](https://user-images.githubusercontent.com/71572688/103488276-fa8fb800-4e13-11eb-9aba-9f2e6920b365.png)

**Comment by RaitGamerGR** [comment]
Может у тебя он залочен?

**Comment by aagrishankov** [comment]
> Может у тебя он залочен?

Тоже так считаю

**Comment by kirilwapj** [comment]
> Может у тебя он залочен?

Просто поставил его, ничего не делал. А как проверить залочен он и разлочить его?

**Comment by aagrishankov** [comment]
эти хэтчи созданы для постоянной заливки жидкостей, для других целей я их не тестировал. Да и не нужны они для сменных жиж, хочешь менять жидкости - делай обычных хэтчи
