### ISSUE TITLE
Да будет свет!

### ISSUE THREAD

**Issue by Spartak1997** [GT-IMPACT/IMPACT-1#139]
Опишите ваше предложение
Убрать проверку воздуха в мультиблоках грега для того, чтобы комфортно использовать светильники с большой территорией покрытия, так как такие вещи как прожекторы из Galacricraft и Greg's Light создают невидимые источники света из-за которых структура мультиблока может "сломаться".

Какие проблемы решит/добавит ваше предложение?
База будет освещена и машины из-за этого не пострадают.

Объясните, почему ваше предложение должны реализовать?
Комфортная игра без подобных недоразумений.

**Comment by aagrishankov** [comment]
Список мультиблоков в студию

**Comment by aagrishankov** [comment]
вроде я все починиль
