### ISSUE TITLE
Бесконечная жидкость в цертус танках

### ISSUE THREAD

**Issue by kirilwapj** [GT-IMPACT/IMPACT-1#14]
В последней версии появился баг с танками с extra cells 2, если в танке хоть 1 ведро жидкости его можно черпать бесконечно. Играю в синг.

**Comment by Pilad** [comment]
А чем черпаешь?

**Comment by kirilwapj** [comment]
Капсулой с ic2

**Comment by kirilwapj** [comment]
![Screenshot_7](https://user-images.githubusercontent.com/71572688/93709756-a7864380-fb49-11ea-8d5c-c8904f0cc161.png)

**Comment by aagrishankov** [comment]
https://github.com/GT-IMPACT/ExtraCells2/commit/66ce5b45a0df70d3d918117a708f8fd853c4a0bb
