### ISSUE TITLE
Хв бур

### ISSUE THREAD

**Issue by LewisSaber** [GT-IMPACT/IMPACT-1#140]
Опишите ваше предложение
Уберите возможность Мв-хв буру заряжатся от нано нагрудника

Какие проблемы решит/добавит ваше предложение?
Бур не будет высасывать весь заряд нагрудника 

Объясните, почему ваше предложение должны реализовать?
Хв бур ето такая вещ которой заряда хватит до поломки, поетому его раз зарядил и до конце хватит, мой бур например на луне забрал у меня весь заряд с нагрудника и умер с почти полной батереей

**Comment by aagrishankov** [comment]
Это сделать невозможно, так как отключатся сразу все инструменты и не будет заряжаться вообще
