### ISSUE TITLE
Крафты через volumetric flask

### ISSUE THREAD

**Issue by kirilwapj** [GT-IMPACT/IMPACT-1#149]
Опишите ваше предложение
Добавить возможность видеть какая жидкость используется в крафте. Бывает так что не хватает какой-то жидкости и хотелось бы знать какой именно. На данный момент аплайт отображает только название "volum
etric flask".
![Screenshot_8](https://user-images.githubusercontent.com/71572688/104130888-e69c0700-537b-11eb-85c6-71ed8d365ba5.png)

Какие проблемы решит/добавит ваше предложение?
Не нужно будет выискивать какой жидкости не хватает.

Объясните, почему ваше предложение должны реализовать?
Учитывая что вы не рекомендуете использовать жид. интерфейсы и в дальнейшем не будете проводить по ним никаких работ, то оптимальный вариант будет крафт через фласки в обычных интерфейсах. На данный момент есть такое неудобство при их использовании. Я считаю было бы уместно добавить в интерфейс автокрафта отображение нижней подсказки (хз как она называется точно).
![Screenshot_9](https://user-images.githubusercontent.com/71572688/104130917-13501e80-537c-11eb-9fad-7bfb6060b3a6.png)

**Comment by aagrishankov** [comment]
![image](https://user-images.githubusercontent.com/50260829/104219537-d74ab580-5470-11eb-9825-2d6811b9b344.png)
![image](https://user-images.githubusercontent.com/50260829/104219574-e16cb400-5470-11eb-839a-1c0de1250cf1.png)
