### ISSUE TITLE
Не работает EnderIO Dimensional Transceiver

### ISSUE THREAD

**Issue by Pixartus** [GT-IMPACT/IMPACT-1#15]
Какую версию модпака вы используете?
1.0 rc2

Вы играете в одиночке или на сервере?
На локальном сервере

Опишите ошибку (Если нужно, приложите скриншоты)
После обновления Dimensional Transceiver принимает максимум 80 rf/t. Хотя Upkeep у него установлен в 500. И он ничего не принимает и не передает
![image](https://user-images.githubusercontent.com/71582556/93705342-18673480-fb25-11ea-8449-389f7131a7c2.png)

**Comment by aagrishankov** [comment]
Из-за того что обновили версию EnderIO - могло и такое получится, проверим

**Comment by aagrishankov** [comment]
Проверил трансивер - работает в штатном режиме, все отлично с ним 
![image](https://user-images.githubusercontent.com/50260829/93713360-7fb4d100-fb85-11ea-98f3-265adedc8f44.png)

**Comment by Pilad** [comment]
конфиг эндер ио сотри и попробуй опять.

**Comment by aagrishankov** [comment]
> конфиг эндер ио сотри и попробуй опять.

конфиг тот, что в сборке

**Comment by aagrishankov** [comment]
@Pixartus проверь еще раз, воспроизводится ли этот баг, и правильно ли ты настраиваешь трансивер

**Comment by Pixartus** [comment]
Ошибка была только на трансиверах созданных до патча. После обнуления и новые созданные вроде работают нормально.

**Comment by starstack14** [comment]
@4gname если вы портировали с 1.12.2 то это нормально, так же и на GTNH было
