### ISSUE TITLE
Не перерабатываются продукты после 1го этапа дистиляции наквахимии в HMS

### ISSUE THREAD

**Issue by Moroka** [GT-IMPACT/IMPACT-1#151]
Какую версию модпака вы используете?
Latest

Вы играете в одиночке или на сервере?
ZS

Опишите ошибку (Если нужно, приложите скриншоты)
Не запускается Heavy Metal Cyclone для рецептов дистилляции Clear Naquadah Luquid

Какие изменения вы предлагаете?
Fix it

**Comment by FireWarrior2** [comment]
@Moroka только что проверил, все Complicated жидкости вполне перерабатываются в циклоне. Clear Naquadah Liquid и не должен, его нужно в дист. башню
![2021-01-13_01 23 24](https://user-images.githubusercontent.com/18097458/104381771-0ed36380-553e-11eb-9d87-bdc86de351ae.png)

**Comment by Moroka** [comment]
Возможно не очень понятно написал, у меня complicated жидкости не перерабатываются
2 лув энержи хатча(энергия есть), 4 инпут флуид хатча с complicated наквадах жижами после дистиляции, 1 аутпут бас, 1 аутпут флуид хатч, мейтенанс - ок. Даже не пытается ничего крафтить, т.е. как будто рецепта нету на самом деле

**Comment by FireWarrior2** [comment]
@Moroka попробуй 2 4А ИВ хетча

**Comment by Moroka** [comment]
Я пробовал 4А лув - не помогло

**Comment by Moroka** [comment]
Почти добрался до зпм, надеюсь хоть на нем заведется

**Comment by FireWarrior2** [comment]
Ну может тогда в сервере проблема, не знаю.. в сингле работает

**Comment by FireWarrior2** [comment]
Вообщем, надо поставить инпут бас.
Еще криво воспринимает многоамперные хетчи, я запустил на двух ив.
И он не сможет обработать несколько жиж в разных инпутах (легкую, среднюю, тяжелую, например)
