### ISSUE TITLE
Слитки без газа

### ISSUE THREAD

**Issue by LewisSaber** [GT-IMPACT/IMPACT-1#152]
Опишите ваше предложение
Добавить рецепт металов которые могут плавится только без газа  чтоб могли плавится даже при микросхеме №11
Пример: Blacksteel может плавится только при микросхеме №1, добавте рецепт чтобы она могла и при микросхеме №11 плавится

Какие проблемы решит/добавит ваше предложение?
Не надо делать больше доменок под несколько металов

Объясните, почему ваше предложение должны реализовать?
Ну легче же .

**Comment by aagrishankov** [comment]
Не все металы плавятся без жидкости. То что легче - не аргументировано никак.

**Comment by LewisSaber** [comment]
Есть такие что только без жидкости. и они плавятся только через микросхему 1, поетому ты либо ставиш ее вместе с №11 и надеешся что оно будет плавить то что надо с газом, либо строиш дополнительные доменки

**Comment by aagrishankov** [comment]
Так ставь 2 доменки и мультихэтч, проще же

**Comment by LewisSaber** [comment]
Можно зделать тогда чтоб доменка имела режим сепарации басов как было в Processian array

**Comment by aagrishankov** [comment]
Ну вот, это уже более логичное предложение)

**Comment by RaitGamerGR** [comment]
Даёшь разделенные басы доменке!
