### ISSUE TITLE
Super Input Bus

### ISSUE THREAD

**Issue by RaitGamerGR** [GT-IMPACT/IMPACT-1#158]
**Опишите ваше предложение**
Добавить инпут бас на 256 слотов для пэкеджера и добавить возможность его работы с присутствием в басе неполного кол-ва компонентов для другого рецептов (В бассе лежит 7 тини пайл редстоуна 17 тини пайл индия 1 смол пайл стекла, пэкеджер собирает индий вне зависимости от того, в каком слоте он находится) или дать возможность встроить супербуффер в пэкеджер с определением его как инпут бас

**Какие проблемы решит/добавит ваше предложение?**
Решит проблему лагов вызванную супербуффером проверяющим 256 слотов каждый тик и упростит сборку пылек простым складированием их без всяких промежуточных хранилищ

**Объясните, почему ваше предложение должны реализовать?**
Потому что я написал ишшую.

**Comment by RaitGamerGR** [comment]
Возможно добавить возможность отключать сепарацию басов у пэкеджера, так как слышал о недостаточном объеме супебуффера даже при разделении на буффер для тини и смол пылек. Сам подтвердить не могу, не дошел до нужного уровня. Отключение сепарации можно реализовать стуком обычного молотка по контроллеру(Сейчас он включает\выключает автоинпут\аутпут предметов и жиж, что бесполезно, кек).

**Comment by aagrishankov** [comment]
> Возможно добавить возможность отключать сепарацию басов у пэкеджера, так как слышал о недостаточном объеме супебуффера даже при разделении на буффер для тини и смол пылек. Сам подтвердить не могу, не дошел до нужного уровня. Отключение сепарации можно реализовать стуком обычного молотка по контроллеру(Сейчас он включает\выключает автоинпут\аутпут предметов и жиж, что бесполезно, кек).

Сепарация отключается отверткой шифт + клик по контролеру

**Comment by aagrishankov** [comment]
Не реализуемо, закрываю

**Comment by aagrishankov** [comment]
Сделан большой бас только для мультиблочного пакеджера
