### ISSUE TITLE
Мультиблочный ассемблер не воспринимает Input Bus

### ISSUE THREAD

**Issue by Pixartus** [GT-IMPACT/IMPACT-1#16]
Какую версию модпака вы используете?
1.0 rc2

Вы играете в одиночке или на сервере?
На локальном сервере

Опишите ошибку (Если нужно, приложите скриншоты)
Мультиблочный ассемблер не воспринимает InputBus на некоторых местах и не видит там предметы.
Хотя контроллер говорит что структура корретная но он эти блоки даже не перекрашивает.
![image](https://user-images.githubusercontent.com/71582556/93705414-ce328300-fb25-11ea-9ef0-7115ecd7cda3.png)

**Comment by aagrishankov** [comment]
Не правильно собрал структуру потому что, внимательно смотри чертеж, в этих местах, где стоят басы, вообще нет ничего, там воздух
