### ISSUE TITLE
Blueprint не работает

### ISSUE THREAD

**Issue by ZherebinVR** [GT-IMPACT/IMPACT-1#161]
Какую версию модпака вы используете?
Последняя 1.0.0.2

Вы играете в одиночке или на сервере?
Сервер

Опишите ошибку (Если нужно, приложите скриншоты)
Blueprint не отображает конструкцию следующих многоблоков:
Vacuum Freezer
Assembly Line
Combustion Engine Mk1
Combustion Engine Mk2
Coke Oven
Electric Blast Furnace (кубы из тека вместо хитпруфов и коилов)
![image](https://user-images.githubusercontent.com/55599416/105081608-73913f80-5aa3-11eb-8804-1406fa1e04fb.png)
А так же в креативе не ставятся фрейм боксы по шифт+клик.

Какие изменения вы предлагаете?
Добавить отображения конструкций для этих многоблоков.
Добавить возможность в креативе ставить фрейм боксы по шифт+клик

**Comment by aagrishankov** [comment]
Фрейм боксы не могут ставится, это не поправить. Остальное исправлю)
