### ISSUE TITLE
Квантовые кольца потребляют 32кВ вместо 8кВ!

### ISSUE THREAD

**Issue by MineSV** [GT-IMPACT/IMPACT-1#169]
Какую версию модпака вы используете?
1.0.0.2

Вы играете в одиночке или на сервере?
одиночка

Опишите ошибку (Если нужно, приложите скриншоты)
При запуске даже одного квантового кольца энергопотребление МЕ мети возрастает на 16кВ, вместо заверенных 4!

![2021-01-29_10 22 18](https://user-images.githubusercontent.com/71754209/106235287-40c21680-621c-11eb-97e9-e653e922c8d3.png)

![2021-01-29_10 22 42](https://user-images.githubusercontent.com/71754209/106235293-44559d80-621c-11eb-8c30-6e5fd56ab726.png)

Какие изменения вы предлагаете?
Исправить сей баг.

**Comment by aagrishankov** [comment]
уже пофикшенно
