### ISSUE TITLE
Интеграция БХР с Cleanroom

### ISSUE THREAD

**Issue by Spartak1997** [GT-IMPACT/IMPACT-1#17]
Какую версию модпака вы используете?
1.0 rc2

Вы играете в одиночке или на сервере?

Опишите ошибку (Если нужно, приложите скриншоты)
Большой химический реактор выполняет рецепты вне зависимости от среды.

Какие изменения вы предлагаете?
Обязательное введение бхр в чистую комнату.

**Comment by aagrishankov** [comment]
https://github.com/GT-IMPACT/GT5.09OFFBEAT/commit/3c210f8d98441102d8f419ddd3afbb924d9f6331
