### ISSUE TITLE
Угольная пыль, мелкий конфликт рецепта в миксере.

### ISSUE THREAD

**Issue by Zebrix** [GT-IMPACT/IMPACT-1#172]
Какую версию модпака вы используете?
1.0.0.2

Вы играете в одиночке или на сервере?
Сервер.

Опишите ошибку (Если нужно, приложите скриншоты)
Угольная пыль в миксере с конфигом 2 мешается и в электросталь, и в жидкую черную краску (из воды).

Какие изменения вы предлагаете?
Поменять.

**Comment by FireWarrior2** [comment]
Дубль
https://github.com/GT-IMPACT/IMPACT-MODPACK/issues/109
