### ISSUE TITLE
Некорректная работа мультиблоков c 4А хетчами

### ISSUE THREAD

**Issue by Pixartus** [GT-IMPACT/IMPACT-1#174]
Какую версию модпака вы используете?
1.0.0.2

Вы играете в одиночке или на сервере?
Сервер

Опишите ошибку (Если нужно, приложите скриншоты)
Многоблоки работают в 4 раза быстрее без параллелей
Выполнял рецепт на 4А IV
![image](https://user-images.githubusercontent.com/71582556/106655252-c984dd80-65a1-11eb-9636-ebaa8c0616dd.png)

Выполнялся в 4 раза быстрее (за 8 секунд) и потреблял из буфера 40к.
Сканер при этом показывал:
![image](https://user-images.githubusercontent.com/71582556/106655454-0a7cf200-65a2-11eb-8186-ee94e3e9a90f.png)

**Comment by aagrishankov** [comment]
у меня все ок 
![image](https://user-images.githubusercontent.com/50260829/106979139-42e22300-6790-11eb-9b78-fcece511189f.png)

**Comment by Pixartus** [comment]
Проверил в сингле, сразу после создания работает с ускорением
![image](https://user-images.githubusercontent.com/71582556/107334005-dd0ed780-6abe-11eb-9388-3b845ea38c1b.png)
После перезахода в сингл/рестарта сервера начинает работать нормально но тот рецепт который выполнялся с ускорением теряется
![image](https://user-images.githubusercontent.com/71582556/107334282-2eb76200-6abf-11eb-9028-22c4ee01db9e.png)
После замены хетча на 1A LuV, процесс не идет, висит на 0, при этом енергию потребляет
![image](https://user-images.githubusercontent.com/71582556/107334423-60302d80-6abf-11eb-8b3b-4d4ef27d4903.png)
И после перезахода прогрес начинает идти нормально
