### ISSUE TITLE
Добавить в вайлу время работы примитивной доменки.

### ISSUE THREAD

**Issue by LeninSaintP** [GT-IMPACT/IMPACT-1#183]
Опишите ваше предложение / Describe your proposal

Добавить в вайлу время работы (операции) для примитивной доменки. До бронзовой не добрался, но наверное и туда.

Какие проблемы решит/добавит ваше предложение? / What problems will your proposal solve / add?

Будет видно сколько времени тратиться на операцию.

Объясните, почему ваше предложение должны реализовать? / Explain why your proposal should be implemented?

**Comment by maxim79135** [comment]
![image](https://user-images.githubusercontent.com/35911642/108310348-4a5bf000-71c4-11eb-8578-d9f51aa1fd47.png)
