### ISSUE TITLE
Бойлеры дорогие

### ISSUE THREAD

**Issue by RaitGamerGR** [GT-IMPACT/IMPACT-1#185]
**Опишите ваше предложение / Describe your proposal**
Вернуть рецепт стальному бойлеру

**Какие проблемы решит/добавит ваше предложение? / What problems will your proposal solve / add?**
Уууууу ДОРАГА
![image](https://user-images.githubusercontent.com/70205464/107847767-71e73d00-6dff-11eb-9c4f-2592433378dc.png)

**Объясните, почему ваше предложение должны реализовать? / Explain why your proposal should be implemented?**
Потому что Сашка инженер не одобряет

**Comment by aagrishankov** [comment]
тут нормас все
