### ISSUE TITLE
Карьер на Энцеладе

### ISSUE THREAD

**Issue by FireWarrior2** [GT-IMPACT/IMPACT-1#188]
Какую версию модпака вы используете? / Which modpack version are you using?
1.0.0.2

Вы играете в одиночке или на сервере? / Are you playing single or on a multiplayer?
одиночка

Опишите ошибку (Если нужно, приложите скриншоты). / Describe the bug (Attach screenshots if needed).
С карьером на Энцеладе происходит какая-то дичь: после постройки "направляющие" и "бур" улетают в соседние чанки, и ничего не работает. На других планетах такого не наблюдалось.
![2021-02-16_12 47 33](https://user-images.githubusercontent.com/18097458/108059120-14a0f500-7066-11eb-9d1c-208109b32709.png)

Какие изменения вы предлагаете? / What changes do you suggest?
Постараться пофиксить это

**Comment by aagrishankov** [comment]
Карьер на неопределенный срок будет отключен.

Причина: роняет сервер.
