### ISSUE TITLE
Дюп железа на ULV Portable Tank

### ISSUE THREAD

**Issue by Zebrix** [GT-IMPACT/IMPACT-1#189]
Какую версию модпака вы используете? / Which modpack version are you using?
1.0.0.2

Опишите ошибку (Если нужно, приложите скриншоты). / Describe the bug (Attach screenshots if needed).
![image](https://user-images.githubusercontent.com/26423111/108363744-d8b58d80-7227-11eb-961e-1667d172d5be.png)

Какие изменения вы предлагаете? / What changes do you suggest?
Не то чтоб особо выгодно и критично, но имеется.

**Comment by aagrishankov** [comment]
ты энергии больше тратишь на раскладку, чем на производство, не думаю что это дюп

**Comment by Zebrix** [comment]
Ну просто к тому что из энергии бесконечное железо получается. А то что не слишком дешево, что же поделать - халява она всегда дорогая.)

**Comment by aagrishankov** [comment]
ну так смотри у тебя сталь тут дюпается 4 штучки по факту, ты за 20 секунд делаешь 4 слитка этих стали, не выгодный дюп, и энерго затратный, при условии что железо - мусор) а крафтить каждый раз танк - такое, крафт нудный, как для капсул, так и для пластин

ишую закрою)
