### ISSUE TITLE
Заряды всяких электрогадов V2

### ISSUE THREAD

**Issue by RaitGamerGR** [GT-IMPACT/IMPACT-1#191]
Опишите ваше предложение / Describe your proposal
Изменить заряд инструментов, броней, батбуфферов ИК в связи с изменением ёмкости Энергокристаллов и Лапотронов:
Energypack 10M 
Advanced Lappack 25M
MFE 20M
Charge Pad (MFE) 20M
NanoSuit Helmet 5M
NanoSuit Bodyarmor 5M
NanoSuit Leggings 5M
NanoSuit Boots 5M
Advanced NanoChestPlate 30M
Nano Saber 25M
Ultimate Lappack 75M
MFSU 100M
Charge Pad (MFSU) 100M
QuantumSuit Helmet 280М
QuantumSuit Bodyarmor 280М
QuantumSuit Leggings 280М
QuantumSuit Boots 280М
GraviChestPlane 1,5 G
K2P4 12,5 G

Какие проблемы решит/добавит ваше предложение? / What problems will your proposal solve / add?
Ёмкость полученной вещи будет соответствовать ёмкости использованных в крафте аккумуляторов

Объясните, почему ваше предложение должны реализовать? / Explain why your proposal should be implemented?
Потому что на данный момент ёмкость батареек теряется

**Comment by RaitGamerGR** [comment]
Relocator 60М

**Comment by RaitGamerGR** [comment]
Mining Laser 100 M
Vajra 25 M

**Comment by aagrishankov** [comment]
- [x] Energypack 10M
- [x] Advanced Lappack 25M
- [ ] MFE 20M
- [ ] Charge Pad (MFE) 20M
- [x] NanoSuit Helmet 5M
- [x] NanoSuit Bodyarmor 5M
- [x] NanoSuit Leggings 5M
- [x] NanoSuit Boots 5M
- [x] Advanced NanoChestPlate 30M
- [x] Nano Saber 25M
- [x] Ultimate Lappack 75M
- [ ] MFSU 100M
- [ ] Charge Pad (MFSU) 100M
- [x] QuantumSuit Helmet 280М
- [x] QuantumSuit Bodyarmor 280М
- [x] QuantumSuit Leggings 280М
- [x] QuantumSuit Boots 280М
- [x] GraviChestPlane 1,5 G
- [x] K2P4 12,5 G
- [x] Relocator 60М
- [x] Mining Laser 100 M
- [x] Vajra 25 M

для мехов ик2 не поддерживает таких больших значений

**Comment by Pilad** [comment]
Ага, только на этом тире такие заряды как заряжать? Емкости огромные стали.  Это или чарджпады икашные фиксить на емкость так же и увеличивать им скорость заряда или локеры разгонять.

**Comment by LewisSaber** [comment]
> Ага, только на этом тире такие заряды как заряжать? Емкости огромные стали. Это или чарджпады икашные фиксить на емкость так же и увеличивать им скорость заряда или локеры разгонять.

Battery charger и turbo charger никто не отменял

**Comment by Pilad** [comment]
> 
> 
> > Ага, только на этом тире такие заряды как заряжать? Емкости огромные стали. Это или чарджпады икашные фиксить на емкость так же и увеличивать им скорость заряда или локеры разгонять.
> 
> Battery charger и turbo charger никто не отменял

Может и так, но и с такими зарядами при таком низком напряжении потребуется источник в сотни ампер.

**Comment by aagrishankov** [comment]
> Может и так, но и с такими зарядами при таком низком напряжении потребуется источник в сотни ампер.

дигитал трансформер в помощь

**Comment by Pilad** [comment]
> 
> 
> > Может и так, но и с такими зарядами при таком низком напряжении потребуется источник в сотни ампер.
> 
> дигитал трансформер в помощь

Понятно, матрешку делаем. Чтоб зарядить броню на 512/2048 нужно взять ДТ на 2кк )))

**Comment by RaitGamerGR** [comment]
> > > Может и так, но и с такими зарядами при таком низком напряжении потребуется источник в сотни ампер.
> > 
> > 
> > дигитал трансформер в помощь
> 
> Понятно, матрешку делаем. Чтоб зарядить броню на 512/2048 нужно взять ДТ на 2кк )))

Не думаю, что это будет проблемой. Когда поднимали заряд нанки первый раз жалоб никаких небыло, хотя ап был достаточно внушительным. Подождать на 20 секунд больше проблемы не составляет

**Comment by Pilad** [comment]
> 
> 
> > > > Может и так, но и с такими зарядами при таком низком напряжении потребуется источник в сотни ампер.
> > > 
> > > 
> > > дигитал трансформер в помощь
> > 
> > 
> > Понятно, матрешку делаем. Чтоб зарядить броню на 512/2048 нужно взять ДТ на 2кк )))
> 
> Не думаю, что это будет проблемой. Когда поднимали заряд нанки первый раз жалоб никаких небыло, хотя ап был достаточно внушительным. Подождать на 20 секунд больше проблемы не составляет

Я нанкой даже никогда и не пользовался, может потому и нет жалоб. А вот про квант и броню с грависьюита уже писали,что затрахаешся заряжать. Как и инструменты с поднятыми зарядами.

**Comment by RaitGamerGR** [comment]
> > > > > Может и так, но и с такими зарядами при таком низком напряжении потребуется источник в сотни ампер.
> > > > 
> > > > 
> > > > дигитал трансформер в помощь
> > > 
> > > 
> > > Понятно, матрешку делаем. Чтоб зарядить броню на 512/2048 нужно взять ДТ на 2кк )))
> > 
> > 
> > Не думаю, что это будет проблемой. Когда поднимали заряд нанки первый раз жалоб никаких небыло, хотя ап был достаточно внушительным. Подождать на 20 секунд больше проблемы не составляет
> 
> Я нанкой даже никогда и не пользовался, может потому и нет жалоб. А вот про квант и броню с грависьюита уже писали,что затрахаешся заряжать. Как и инструменты с поднятыми зарядами.

На том тире есть турбочарджер и трансформатор на 256А и турба чарджер на 120А
![image](https://user-images.githubusercontent.com/70205464/109123651-23209800-775b-11eb-8694-8dfdab81e2be.png)
![image](https://user-images.githubusercontent.com/70205464/109123736-37649500-775b-11eb-990d-d3888ec85ee6.png)

**Comment by aagrishankov** [comment]
в чем проблема зарядить? ничего не поменялось, стало еще удобнее, чем реже заряжаешься - тем лучше

**Comment by Pilad** [comment]
> 
> 
> > > > > > Может и так, но и с такими зарядами при таком низком напряжении потребуется источник в сотни ампер.
> > > > > 
> > > > > 
> > > > > дигитал трансформер в помощь
> > > > 
> > > > 
> > > > Понятно, матрешку делаем. Чтоб зарядить броню на 512/2048 нужно взять ДТ на 2кк )))
> > > 
> > > 
> > > Не думаю, что это будет проблемой. Когда поднимали заряд нанки первый раз жалоб никаких небыло, хотя ап был достаточно внушительным. Подождать на 20 секунд больше проблемы не составляет
> > 
> > 
> > Я нанкой даже никогда и не пользовался, может потому и нет жалоб. А вот про квант и броню с грависьюита уже писали,что затрахаешся заряжать. Как и инструменты с поднятыми зарядами.
> 
> На том тире есть турбочарджер и трансформатор на 256А и турба чарджер на 120А
> ![image](https://user-images.githubusercontent.com/70205464/109123651-23209800-775b-11eb-8694-8dfdab81e2be.png)
> ![image](https://user-images.githubusercontent.com/70205464/109123736-37649500-775b-11eb-990d-d3888ec85ee6.png)

то есть чтоб полноценно зарядить 512/2048 броник нужно ЗПМ напругу. Гениально )

**Comment by LewisSaber** [comment]
Зделать какое-то улучшения броне на без конечный заряд, типа как ртг в факторке

**Comment by aagrishankov** [comment]
> Зделать какое-то улучшения броне на без конечный заряд, типа как ртг в факторке

апи ик2 перепишешь не сломав остальные все моды?

**Comment by LewisSaber** [comment]
Нет (

**Comment by aagrishankov** [comment]
> Нет (

и я тоже)
