### ISSUE TITLE
Место под шейпы\молды

### ISSUE THREAD

**Issue by RaitGamerGR** [GT-IMPACT/IMPACT-1#194]
**Опишите ваше предложение / Describe your proposal**
Добавить дополнительные слоты механизмам, работающим со множеством форм/схем(Экструдер, слидифаер, ассемблер, возможно аллой смелтер, бендер, миксер) для их хранения.

**Какие проблемы решит/добавит ваше предложение? / What problems will your proposal solve / add?**
Уберет необходимость ставить рядом с механизмами дополнительные инвентари для хранения форм/конфигурационных схем, добавит удобство ручного использования данных механизмов.

**Объясните, почему ваше предложение должны реализовать? / Explain why your proposal should be implemented?**
На данный момент для комфортного использования некоторых механизмов для быстрого доступа к формам/схемам применяют слоты не предназначенные для хранения там форм(Слот под батарейку, еще какой-то непонятный слот). Так же из-за обилия форм ставят дополнительный инвентарь рядом с механизмом. Схемы же приходится или хранить в слотах механизма, что может привести к конфликтам, или постоянно переконфигурировать.

**Comment by RaitGamerGR** [comment]
Механизмы:
Ассемблер
Солидифаер
Аллой смелтер
Бендер
Вайер ассемблер
Миксер
Экструдер
Лазер енгрейвер
Форминг пресс
Электролизер
Принтер
Сканер

**Comment by aagrishankov** [comment]
Сразу скажу нет, потому что это будет вызывать проблемы очень серьзеные, чтобы решить эту проблему нужно переписывать весь грег, а это сломает интеграции с адонами

**Comment by Pilad** [comment]
Добавить блок/сундук. Как в иммерсиве переносной. И он может использоваться в структуре многоблока.

**Comment by aagrishankov** [comment]
это не реализуемо в греге, все слоты всегда проверяются

**Comment by RaitGamerGR** [comment]
Да даже тот же тинкеостол умеет в похожее, но нет так нет

**Comment by aagrishankov** [comment]
тинкер стол это не грег)

**Comment by RaitGamerGR** [comment]
Есть такая проблема, да)

**Comment by maxim79135** [comment]
Может теоретические можно сделать внутренний буфер, и гуи рядом. В нем лежать все шейпы. На начальной стадии неудобно с ними возиться, согласен. Но после уже многоблок есть с басами под каждый шейп

**Comment by Pilad** [comment]
> тинкер стол это не грег)

Сделай им выемку в многоблоке,пусть сундук ставят))
