### ISSUE TITLE
маленький фикс описания солнечного бойлера

### ISSUE THREAD

**Issue by zetcool90** [GT-IMPACT/IMPACT-1#195]
Какую версию модпака вы используете? / Which modpack version are you using?
1.0.0.2

Вы играете в одиночке или на сервере? / Are you playing single or on a multiplayer?

сервер
Опишите ошибку (Если нужно, приложите скриншоты). / Describe the bug (Attach screenshots if needed).
в описании солнечного бойлера написано что чтоб снять кальцирование с бойлера нужно его снять и поставить 

Какие изменения вы предлагаете? / What changes do you suggest?
поменять на кликнуть пкм молотом по бойлеру

**Comment by maxim79135** [comment]
![image](https://user-images.githubusercontent.com/35911642/108807443-85d82f00-75b5-11eb-97a7-9358f466deb5.png)
Fixed
