### ISSUE TITLE
Батарейный и турбо зарядник

### ISSUE THREAD

**Issue by FireWarrior2** [GT-IMPACT/IMPACT-1#196]
Опишите ваше предложение / Describe your proposal
У батарейного зарядника прописать, сколькими амперами он заряжает предмет.
У турбо зарядника проверить тултип (120А/item), т.к. в ходе теста он потреблял 64А, заряжая 1 предмет.

Какие проблемы решит/добавит ваше предложение? / What problems will your proposal solve / add?
-

Объясните, почему ваше предложение должны реализовать? / Explain why your proposal should be implemented?
-

**Comment by aagrishankov** [comment]
120А он выдает из капасити своего, когда разряжается капасити выдает сколько ты ему подашь, подниму буфер внутренний и будет хорошо
