### ISSUE TITLE
Ztones microblocks

### ISSUE THREAD

**Issue by rbb30** [GT-IMPACT/IMPACT-1#197]
Describe your proposal
Add Ztones blocks to the microblocks.cfg file.

What problems will your proposal solve / add?
Ztones blocks aren't by default compatible into microblocks adding them in the config file will allow them to be cut into microblocks.

Explain why your proposal should be implemented?
This would allow Ztones blocks to be cut into microblocks live every other block is.

**Comment by aagrishankov** [comment]
its already fixed :)
