### ISSUE TITLE
Добавить в крафт многоблочного ассемблера необходимость в радоне

### ISSUE THREAD

**Issue by EvgenPrig** [GT-IMPACT/IMPACT-1#2]
![image](https://user-images.githubusercontent.com/70282409/91517206-ee3f9f80-e8f5-11ea-9aa9-0b21428923dc.png)
В крафте контроллера многоблочного ассемблера нет компонентов создающихся с радоном, что позволяет пропустить добычу радона для крафта EV circuit assembler

Предлагаю либо добавить IV emitter, либо радоновую линзу в крафт контроллера

**Comment by aagrishankov** [comment]
Используй шаблон для ишуе, в следующий раз
