### ISSUE TITLE
Сингл- и Мультитанки уничтожают жидкости после перезахода в мир

### ISSUE THREAD

**Issue by FireWarrior2** [GT-IMPACT/IMPACT-1#20]
Какую версию модпака вы используете?
1.0 rc2

Вы играете в одиночке или на сервере?
одиночка

Опишите ошибку (Если нужно, приложите скриншоты)
Сингл- и Мультитанки уничтожают хранящиеся в них жидкости после перезахода в мир.
1) До выхода из мира
![2020-09-23_22 35 58](https://user-images.githubusercontent.com/18097458/94061549-374c1c00-fdee-11ea-852e-7a6e4362d1ff.png)
2) После входа в мир
![2020-09-23_22 36 49](https://user-images.githubusercontent.com/18097458/94061554-387d4900-fdee-11ea-9ae4-aee606123d36.png)

**Comment by aagrishankov** [comment]
как быстро ты из мира вышел после наполнения танка?

**Comment by FireWarrior2** [comment]
На примере на скрине - довольно быстро.
Но ранее прошло достаточно много времени до выхода, после того, как залил несколько тысяч ведер азота, кислорода и сероводорода..

**Comment by aagrishankov** [comment]
https://github.com/GT-IMPACT/Impact-Core/commit/b13c03bfa217366724bba136a002b33a9d5feaac
