### ISSUE TITLE
Батарейка не дает интерфейсу загрузить ресурсы

### ISSUE THREAD

**Issue by FireWarrior2** [GT-IMPACT/IMPACT-1#200]
Какую версию модпака вы используете? / Which modpack version are you using?
1.0.0.2

Вы играете в одиночке или на сервере? / Are you playing single or on a multiplayer?
одиночка

Опишите ошибку (Если нужно, приложите скриншоты). / Describe the bug (Attach screenshots if needed).
Батарейка не дает интерфейсу загрузить ресурсы (в компонент ассемблере была та же проблема). На видео показано, как:
https://youtu.be/S9P6fOf-yRI

Какие изменения вы предлагаете? / What changes do you suggest?
Постараться это исправить

**Comment by aagrishankov** [comment]
Столкнулся сам, это изза блокинг мода, пофиксить врятли получится, аешку трогать - такое
