### ISSUE TITLE
Architecture Module for Microblocks

### ISSUE THREAD

**Issue by itsmekasta** [GT-IMPACT/IMPACT-1#201]
Hey, 

I noticed that Architecture Module is missing the Microblocks support on 1.0.1.0. 

Any plans of adding that with the next patch? :)

![](https://i.imgur.com/OMMgyiH.png)

**Comment by aagrishankov** [comment]
oops, I forgot to add ..

**Comment by itsmekasta** [comment]
~~Any way for you to upload the new microblocks.cfg with the concrete support separately as manual download? :)~~

Actually nvm, we are on git, I can just get the new file from here.
