### ISSUE TITLE
Add GUI to Extra Utilities Fluid Trash Can

### ISSUE THREAD

**Issue by Discusser** [GT-IMPACT/IMPACT-1#203]
Опишите ваше предложение / Describe your proposal
Make ExU2 Fluid Trash Cans have a GUI, that way you can just put a cell with a fluid for example, and you get an empty cell back.
![image](https://user-images.githubusercontent.com/47938380/110245590-9486f480-7f6c-11eb-9cd8-c24f78df29a8.png)
(an idea of what it would look like)

Какие проблемы решит/добавит ваше предложение? / What problems will your proposal solve / add?
No need to use portable tanks every time you wanna empty a fluid cell.

Объясните, почему ваше предложение должны реализовать? / Explain why your proposal should be implemented?
Quality of Life feature.

**Comment by aagrishankov** [comment]
Most likely, I will add an void mode for all tanks, and then this will make no sense
