### ISSUE TITLE
Хлорка дорогая, не удоляй!

### ISSUE THREAD

**Issue by RaitGamerGR** [GT-IMPACT/IMPACT-1#204]
**Какую версию модпака вы используете? / Which modpack version are you using?**
Новейшую, последнюю.

**Вы играете в одиночке или на сервере? / Are you playing single or on a multiplayer?**
Оффициальный сервер.

**Опишите ошибку (Если нужно, приложите скриншоты). / Describe the bug (Attach screenshots if needed).**
При производстве Silicone Rubber в никуда исчезает хлор.
![image](https://user-images.githubusercontent.com/70205464/110359999-3bdc5800-804f-11eb-9521-da97b03479e8.png)
![image](https://user-images.githubusercontent.com/70205464/110360095-56aecc80-804f-11eb-88fc-06580c218058.png)

**Какие изменения вы предлагаете? / What changes do you suggest?**
Заменить в рецептах разбавленную соляную кислоту на неразбавленную для рецептов одноблока и многоблока и обеспечения полного возврата хлора.

**Comment by aagrishankov** [comment]
Фикс будет входить в полный рефакторинг химии
