### ISSUE TITLE
Рудогенерация на Макемаке

### ISSUE THREAD

**Issue by FireWarrior2** [GT-IMPACT/IMPACT-1#209]
Какую версию модпака вы используете? / Which modpack version are you using?
1.0.1.2

Вы играете в одиночке или на сервере? / Are you playing single or on a multiplayer?
одиночка

Опишите ошибку (Если нужно, приложите скриншоты). / Describe the bug (Attach screenshots if needed).
Часть руд на Макемаке генерируется прямо на поверхности.
![2021-03-08_13 53 25](https://user-images.githubusercontent.com/18097458/110479589-a3011780-80f6-11eb-9960-5db1148aeddf.png)

Какие изменения вы предлагаете? / What changes do you suggest?
Снизить высоту генерации руд или поднять средний уровень поверхности планеты.

**Comment by aagrishankov** [comment]
Так как планируется новый рудоген, смысла это исправлять особого нету)
