### ISSUE TITLE
Давление на Венере

### ISSUE THREAD

**Issue by FireWarrior2** [GT-IMPACT/IMPACT-1#210]
Какую версию модпака вы используете? / Which modpack version are you using?
1.0.1.2

Вы играете в одиночке или на сервере? / Are you playing single or on a multiplayer?
одиночка

Опишите ошибку (Если нужно, приложите скриншоты). / Describe the bug (Attach screenshots if needed).
Исчезло давление на Венере. Можно ходить без кванта. _effect доволен._
![2021-03-09_16 47 13](https://user-images.githubusercontent.com/18097458/110480517-a052f200-80f7-11eb-9aae-f07e2ddc7cce.png)

Какие изменения вы предлагаете? / What changes do you suggest?
Вернуть давление, Венера все таки)

**Comment by aagrishankov** [comment]
так как отключили вообще, и вроде как не планируется включать, закрываю коммит)
