### ISSUE TITLE
Солнечная радиация и защита от нее#4

### ISSUE THREAD

**Issue by FireWarrior2** [GT-IMPACT/IMPACT-1#211]
Какую версию модпака вы используете? / Which modpack version are you using?
1.0.1.2

Вы играете в одиночке или на сервере? / Are you playing single or on a multiplayer?
одиночка

Опишите ошибку (Если нужно, приложите скриншоты). / Describe the bug (Attach screenshots if needed).
Гравик и к2п4 все также не защищают от радиации.
![2021-03-09_17 02 56](https://user-images.githubusercontent.com/18097458/110482090-52d78480-80f9-11eb-867b-ade67ae45091.png)

Какие изменения вы предлагаете? / What changes do you suggest?
Постараться прикрутить защиту..

**Comment by aagrishankov** [comment]
сделана прямая интеграция, защита все равно не работает, я не знаю как это фиксить

**Comment by FireWarrior2** [comment]
Ну пусть, наверное, ишуе останется пока, может со временем станет понятно, как исправить..
