### ISSUE TITLE
Дрель не умеет складывать в Drawers.

### ISSUE THREAD

**Issue by Zebrix** [GT-IMPACT/IMPACT-1#212]
Какую версию модпака вы используете? / Which modpack version are you using?
1.0.1.2

Вы играете в одиночке или на сервере? / Are you playing single or on a multiplayer?
Сервер.

Опишите ошибку (Если нужно, приложите скриншоты). / Describe the bug (Attach screenshots if needed).
При попытке выложить из инвентаря породу в Drawers, держа в руке дрель, показывает что выложилось. Но на самом деле нет, ткнув в "пустую" ячейку или еще как обновив инвентарь, видим всё на прежнем месте.
P.S. Хотя держа к примеру ключ, глюков не происходит.

**Comment by aagrishankov** [comment]
Это изза того что дрель имеет режимы переключения, не думаю что нужно тратить время на такой бесполезный баг)
