### ISSUE TITLE
Перенос новой карты GS

### ISSUE THREAD

**Issue by FireWarrior2** [GT-IMPACT/IMPACT-1#22]
Опишите ваше предложение
Предлагаю перенести с новых версий Galaxy Space (для 1.7.10) улучшенную карту космоса.
![2020-09-24_12 16 10](https://user-images.githubusercontent.com/18097458/94126989-05c06880-fe61-11ea-9342-ade71437a37d.png)

Какие проблемы решит/добавит ваше предложение?
Плюсы данной карты:
1) Добавлена информация о планетах: тип, класс, параметры атмосферы и поверхности, обитаемость, необходимое снаряжение. При необходимости отключается.
2) Звезду можно выбрать через список.
3) Карта не слетает на солнечную систему при клике в случайное место.

Объясните, почему ваше предложение должны реализовать?
Приличную часть сборки занимает исследование планет, поэтому меню их выбора должно быть удобным и должно показывать параметры планеты, куда собираешься лететь.

P.s. У некоторых планет была улучшена генерация ландшафта, можно и ее попробовать перенести)

**Comment by aagrishankov** [comment]
а код нам дашь, которого нету?)

**Comment by FireWarrior2** [comment]
А там не хотят делиться? Печально..

**Comment by aagrishankov** [comment]
Код закрыт

**Comment by aagrishankov** [comment]
Все что есть в новом GalaxySpace перенесен к нам (Новая карта, Новый метод генерации, скафандр и тд)
