### ISSUE TITLE
Recycling of Solar boilers

### ISSUE THREAD

**Issue by alenbdi** [GT-IMPACT/IMPACT-1#229]
Опишите ваше предложение / Describe your proposal

Предлагаю сделать переработку у Simple Solar Boiler и у High Pressure Solar Boiler.

Какие проблемы решит/добавит ваше предложение? / What problems will your proposal solve / add?

Данное предложение способствует возвращению ресурсов, которые были затрачены на создание бойлеров в начальной  стадии игры.

Объясните, почему ваше предложение должны реализовать? / Explain why your proposal should be implemented?

Большинство игроков использовали данные бойлеры, и хотели бы вернуть часть серебра/стали назад, если можно было.

**Comment by Spartak1997** [comment]
Уже есть рецепт переработки - дизассемблер, аркпечь.
