### ISSUE TITLE
Пересечение рецептов азотной кислоты и закиси азота в БХР

### ISSUE THREAD

**Issue by FireWarrior2** [GT-IMPACT/IMPACT-1#23]
Какую версию модпака вы используете?
1.0 rc2

Вы играете в одиночке или на сервере?
одиночка

Опишите ошибку (Если нужно, приложите скриншоты)
Наблюдается специфичное пересечение рецептов: при недостатке водорода в БХР, производящем азотную кислоту, даже с микросхемой в контроллере, будет производиться закись азота.
![2020-09-27_16 05 22](https://user-images.githubusercontent.com/18097458/94365709-be91dc00-00db-11eb-9d2b-7b17d41a80d2.png)
![2020-09-27_16 07 13](https://user-images.githubusercontent.com/18097458/94365710-bf2a7280-00db-11eb-8a06-f3aecb62ae37.png)

Какие изменения вы предлагаете?
В производство закиси азота добавить микросхему.

**Comment by Spartak1997** [comment]
Fixed it
![2020-10-01_00 19 05](https://user-images.githubusercontent.com/29407630/94741049-3bdb7c00-037c-11eb-8628-c4199284efdd.png)
