### ISSUE TITLE
Рецепты ЯР IC2

### ISSUE THREAD

**Issue by FireWarrior2** [GT-IMPACT/IMPACT-1#235]
Какую версию модпака вы используете? / Which modpack version are you using?
1.0.1.4

Вы играете в одиночке или на сервере? / Are you playing single or on a multiplayer?
одиночка

Опишите ошибку (Если нужно, приложите скриншоты). / Describe the bug (Attach screenshots if needed).
После обновления вылезли удаленные рецепты компонентов реактора IC2
![2021-04-01_00 28 47](https://user-images.githubusercontent.com/18097458/113424639-2a316a80-93d9-11eb-9083-0c2b14c6b4cb.png)

Какие изменения вы предлагаете? / What changes do you suggest?
Отключить их

**Comment by Spartak1997** [comment]
Уже исправлено
