### ISSUE TITLE
Дать возможность отключать канали АЕ не ломая рецепты

### ISSUE THREAD

**Issue by AndriiHalyatovskyy** [GT-IMPACT/IMPACT-1#24]
Опишите ваше предложение
Сейчас, если котлючить контроллер, то исчезают и толстые кабели, что ломает парочку рецептов.

Какие проблемы решит/добавит ваше предложение?
Даст возможность отключать каналы в АЕ

Объясните, почему ваше предложение должны реализовать?
Некоторые игроки играют без каналов

**Comment by Pilad** [comment]
Толстые кабели нужны для 32 каналов. Если нет контроллера, то и нет кабелей.

**Comment by aagrishankov** [comment]
> Толстые кабели нужны для 32 каналов. Если нет контроллера, то и нет кабелей.

рецепты ломаются, решение уже принято, при отрубании не выключать предметы вообще

**Comment by aagrishankov** [comment]
https://github.com/GT-IMPACT/Applied-Energistics-2-Unofficial/commit/3daabbb7bfc30c27760fefebcdf9889e3de5dfcb
