### ISSUE TITLE
Пересекаются рецепты Blast Smelter

### ISSUE THREAD

**Issue by mihaillatyshov** [GT-IMPACT/IMPACT-1#240]
Какую версию модпака вы используете? / Which modpack version are you using?
1.0.1.2 (1.0.1.4)

Вы играете в одиночке или на сервере? / Are you playing single or on a multiplayer?
Сервер

Опишите ошибку (Если нужно, приложите скриншоты). / Describe the bug (Attach screenshots if needed).
Пересекаются рецепты в Blast Smelter
При крафте большого количества Maragin Steel 250, начинает крафтиться Nitonol-60
При крафте одного или двух Maragin Steel 250 все работает нормально, но при автокрафте все ломается 
![1](https://user-images.githubusercontent.com/35631710/114701678-c89fc300-9d2b-11eb-93c0-4ad0b260b634.PNG)

![2](https://user-images.githubusercontent.com/35631710/114701694-cd647700-9d2b-11eb-96ea-aca2ab5bc154.PNG)

Какие изменения вы предлагаете? / What changes do you suggest?
Поменять номер микросхемы, для одного из рецептов

**Comment by FireWarrior2** [comment]
Включи blocking mode в интерфейсе, чтобы много сразу не загружало

**Comment by mihaillatyshov** [comment]
Спасибо за совет, так и сделаю
Но так или иначе, пересечение рецептов стоит пофиксить
