### ISSUE TITLE
Crash when logging in SSP (COFH core)

### ISSUE THREAD

**Issue by Chezzik** [GT-IMPACT/IMPACT-1#241]
Какую версию модпака вы используете? / Which modpack version are you using?
IMPACT 1.0.1.4

Вы играете в одиночке или на сервере? / Are you playing single or on a multiplayer?
single

Опишите ошибку (Если нужно, приложите скриншоты). / Describe the bug (Attach screenshots if needed).
I had just built an industrial pulverizer, and had used it, then logged out.  When I logged back in, I saw the pulverizer briefly with missing textures for 3 blocks (input bus, output bus, controller).  Then the game crashed.

Какие изменения вы предлагаете? / What changes do you suggest?
Fix the crash

The log is here: https://paste.ee/p/QiBQb

**Comment by aagrishankov** [comment]
> [13:08:58] [Server thread/ERROR]: This crash report has been saved to: /home/chezzik/Minecraft/MultiMC-dev/bin/instances/IMPACT-1.0.1.4/.minecraft/crash-reports/crash-2021-04-14_13.08.57-server.txt

pls give me crash

**Comment by Chezzik** [comment]
That portion of the crash report is here: https://paste.ee/p/GH0lo

Sorry, I should have included it initially.

**Comment by aagrishankov** [comment]
This is a standard minecraft crash with any mods, packet loss between the server and the client
