### ISSUE TITLE
Руды GS на поясе Койпера

### ISSUE THREAD

**Issue by FireWarrior2** [GT-IMPACT/IMPACT-1#244]
Какую версию модпака вы используете? / Which modpack version are you using?
1.0.1.4

Вы играете в одиночке или на сервере? / Are you playing single or on a multiplayer?
одиночка

Опишите ошибку (Если нужно, приложите скриншоты). / Describe the bug (Attach screenshots if needed).
Руды Galaxy Space - доломит, кобальт, возможно уран в Поясе Койпера
![2021-04-16_23 44 52](https://user-images.githubusercontent.com/18097458/115082444-969a8680-9f0e-11eb-8cc5-2de69eba1d96.png)
![2021-04-16_23 48 09](https://user-images.githubusercontent.com/18097458/115082446-97cbb380-9f0e-11eb-82e9-33b35af53882.png)

Какие изменения вы предлагаете? / What changes do you suggest?
Их там быть не должно

**Comment by aagrishankov** [comment]
Посмотрел код, там сильно фарш будет после декомпиля, все астероиды полетят, лучше не буду трогать)
