### ISSUE TITLE
Fusion casing Mk IV

### ISSUE THREAD

**Issue by FireWarrior2** [GT-IMPACT/IMPACT-1#248]
Какую версию модпака вы используете? / Which modpack version are you using?
1.0.1.4 экспериментальная

Вы играете в одиночке или на сервере? / Are you playing single or on a multiplayer?
одиночка

Опишите ошибку (Если нужно, приложите скриншоты). / Describe the bug (Attach screenshots if needed).
Нестакающиеся предметы в рецепте
![2021-04-20_14 29 45](https://user-images.githubusercontent.com/18097458/115389353-aa333f00-a1e5-11eb-9658-33d7cb3701b4.png)

Какие изменения вы предлагаете? / What changes do you suggest?
Заменить на какой-то промежуточный предмет типа Neutron reflector parts

**Comment by Spartak1997** [comment]
Fixed
