### ISSUE TITLE
Возможность сжечь все углеводороды с нефтепереработки

### ISSUE THREAD

**Issue by KotovladeletsGT** [GT-IMPACT/IMPACT-1#25]
Опишите ваше предложение
    Хочу предложить возможность залить все углеводороды в газовую турбину для получения энергии. Так как всяких этиленов, пропенов, бутенов и т.д. с нефтепереработки копится огромное количество, а из применений у них только использование для всяких полимеров и заливание в электролизёр, где они разложатся  на водород и углерод в соответствующий пропорциях. Согласитесь, странно, что я не могу получать энергию, сжигая этилен! В жизни он прекрасно горит.    
    Предлагаю сделать все углеводороды с формулой вида CxHy топливом для газовых турбин, энергоплотность которого будет  равна, скажем, (x+y)*20000. Например, для этилена С2Н4: (2+4)*20000=120000 еу/ведро, для бутадиена
С4Н6 = 200000 еу/ведро и т.д.

Какие проблемы решит/добавит ваше предложение?
Появится возможность быстро и просто перерабатывать лишние нефтепродукты в энергию, улучшится реалистичность - в жизни все углеводороды прекрасно горят.

Объясните, почему ваше предложение должны реализовать?
Оно упростит жизнь игрокам и добавит реализма.

**Comment by aagrishankov** [comment]
Будет входить в рефакторинг химии
