### ISSUE TITLE
IMPACT-1.0.1.4 играю на сервере (у лавового бойлера бесконечный резервуар сколько не заливай а также когда он полон то уже не тратит лаву)ошибка появляется раз через раз

### ISSUE THREAD

**Issue by Astat-At** [GT-IMPACT/IMPACT-1#257]
Какую версию модпака вы используете? / Which modpack version are you using?

Вы играете в одиночке или на сервере? / Are you playing single or on a multiplayer?

Опишите ошибку (Если нужно, приложите скриншоты). / Describe the bug (Attach screenshots if needed).

Какие изменения вы предлагаете? / What changes do you suggest?

**Comment by 4gname** [comment]
У бойлера нет буфера, он сразу преобразует жижу в burntime и горит ровно столько, сколько ты в него жижи залил
