### ISSUE TITLE
Читерные провода

### ISSUE THREAD

**Issue by RaitGamerGR** [GT-IMPACT/IMPACT-1#258]
**Какую версию модпака вы используете? / Which modpack version are you using?**
Эксперементальную

**Вы играете в одиночке или на сервере? / Are you playing single or on a multiplayer?**
Офф сервер

**Опишите ошибку (Если нужно, приложите скриншоты). / Describe the bug (Attach screenshots if needed).**
Провода из сплавов: Vibrant Alloy, Energetic Alloy, Redstone Alloy имеют одинаковые потери с изоляцией и без.
![image](https://user-images.githubusercontent.com/70205464/117040746-e05add80-ad12-11eb-9dc0-aef03477e6bd.png)
![image](https://user-images.githubusercontent.com/70205464/117040782-ebae0900-ad12-11eb-8927-3b7fe6694926.png)

**Какие изменения вы предлагаете? / What changes do you suggest?**
Изменить потери у проводов из данных материалов

**Comment by Pilad** [comment]
Остальные так же стоит глянуть:ConductiveIron.ElectricalSteel.EnergeticAlloy.VibrantAlloy.PulsatingIron
Если они есть конечно.

**Comment by RaitGamerGR** [comment]
> Остальные так же стоит глянуть:ConductiveIron.ElectricalSteel.EnergeticAlloy.VibrantAlloy.PulsatingIron
> Если они есть конечно.

Нет их, про вибрант написал
