### ISSUE TITLE
Танки не дружат с кондуитами.

### ISSUE THREAD

**Issue by Zebrix** [GT-IMPACT/IMPACT-1#26]
Какую версию модпака вы используете?
1.0rc2

Вы играете в одиночке или на сервере?
Сервер

Опишите ошибку (Если нужно, приложите скриншоты)
Одноблочный танк принимает капсулы из кондуита, но отдаёт их только со стороны выхода.

Какие изменения вы предлагаете?
Fix it.

**Comment by aagrishankov** [comment]
https://github.com/GT-IMPACT/GT5.09OFFBEAT/commit/0f53340bad75ad1985a27b33d10951cb2de71904
