### ISSUE TITLE
Изменить текстуру воздуха

### ISSUE THREAD

**Issue by Spartak1997** [GT-IMPACT/IMPACT-1#27]
Опишите ваше предложение
Предлагаю изменить текстуру воздуха.

Какие проблемы решит/добавит ваше предложение?
Данное изменение исправит такой недочет, как поиск его в рецептах. Пример тому радон, жидкость не видно на фоне серого интерфейса.

Объясните, почему ваше предложение должны реализовать?
Люди не будут жаловаться на "нерабочие" рецепты.

**Comment by aagrishankov** [comment]
https://github.com/GT-IMPACT/GT5.09OFFBEAT/commit/b968b9fe47712adfd408a970663d9baf2ce6b2b7
