### ISSUE TITLE
Старый новый Display Screen

### ISSUE THREAD

**Issue by RaitGamerGR** [GT-IMPACT/IMPACT-1#271]
Какую версию модпака вы используете? / Which modpack version are you using?
С офф сервера

Вы играете в одиночке или на сервере? / Are you playing single or on a multiplayer?
Офф сервер

Опишите ошибку (Если нужно, приложите скриншоты). / Describe the bug (Attach screenshots if needed).
Large Display Screen из импакт кора можно использовать только для крафтов из опен компутерса и контроллеров многоблоков импактовских. Остальные крафты работают только со старым дисплеем из практикал логистик 
![image](https://user-images.githubusercontent.com/70205464/122241729-7580f280-cecb-11eb-9880-ebd7cb5302f0.png)

Какие изменения вы предлагаете? / What changes do you suggest?
Дать возможность использовать или оба монитора или только импактовский

**Comment by FireWarrior2** [comment]
Дубль
https://github.com/GT-IMPACT/IMPACT-MODPACK/issues/267

**Comment by RaitGamerGR** [comment]
Тогда закрываю
