### ISSUE TITLE
Конфликт рецепта Iron bars

### ISSUE THREAD

**Issue by Zebrix** [GT-IMPACT/IMPACT-1#28]
Какую версию модпака вы используете?
1.0rc2

Вы играете в одиночке или на сервере?
сервер

Опишите ошибку (Если нужно, приложите скриншоты)
Конфликт рецепта Iron bars и Rusry Ladder. Оба используют железные палки и 3 микросхему.

Какие изменения вы предлагаете?
Fix it.

**Comment by Spartak1997** [comment]
https://github.com/GT-IMPACT/Impact-Core/commit/0582ec353248138b9832ad230209627fb25919d8
