### ISSUE TITLE
Расход энергии для улучшенной пиролизки

### ISSUE THREAD

**Issue by Pixartus** [GT-IMPACT/IMPACT-1#29]
Какую версию модпака вы используете?
1.0rc2

Опишите ошибку (Если нужно, приложите скриншоты)
Адвенсед пиролизка как-то странно потребляет электричество при увеличении тира. На mv больше ампера.
Примерное потребление на тирах:
lv - 24
mv - 198
hv - 286
ev - 1547
iv - 7812
luv - 37756
zpm - 170560

Какие изменения вы предлагаете?
Проверить потребление энергии, по возможности опишите формулу как должно расчитываться.

**Comment by aagrishankov** [comment]
Формула расчета: 
EU/t = EU/t(по рецепту) *  количество одновременных рецептов (при паралельности) (без оверклока)

EU/t = EU/t(по рецепту) * количество одновременных рецептов (при паралельности) * оверклок

Параллельность = тир хэтча

Пример:
Тир хэтча - мв
EU/t = EU/t(по рецепту) * 2 (без оверклока) - при условии что можно выполнить 2 рецепта, если рецепт запустить 1, то будет:  

EU/t = EU/t(по рецепту) (без оверклока)

Так как рецепт лв тира, то происходит оверклок до мв тира - x4
EU/t = EU/t(по рецепту) * 2 * 4 (с оверклоком) (спаралельностью)
EU/t = EU/t(по рецепту) * 4 (с оверклоком) (без паралельности)
