### ISSUE TITLE
Много жидкостные хечи

### ISSUE THREAD

**Issue by kirilwapj** [GT-IMPACT/IMPACT-1#290]
Опишите ваше предложение / Describe your proposal
Добавить в много жидкостные хечи возможность загрузки volumetric flasks(аналогично как это сделано в жидкосно-предметном хече. С тем отличием что в хеч на 4 жидкости можно будет одновременно загрузить 4 volumetric flasks, а в хеч на 9 жидкостей - 9 volumetric flasks).
Добавить логику что капсула одной жидкости может занимать только один слот.(Чтобы к примеру капсулы кислорода не могли забить все слоты и для капсул другой жидкости не было места)

Какие проблемы решит/добавит ваше предложение? / What problems will your proposal solve / add?
С такой логикой много жидкостных хечей можно автоматизировать почти все рецепты БХР двумя блоками! Интерефейс(из ме) + много жидкостных хеч. 

Объясните, почему ваше предложение должны реализовать? / Explain why your proposal should be implemented?
Выглядит достаточно удобно. Автоматизация будет такой же простой как и с использованием жидкостных интерфейсов, но без тех багов что доставляет жидкостный интерфейс.

**Comment by aagrishankov** [comment]
Данная механика не будет реализована, так как будет вызывать очень много лагов.
