### ISSUE TITLE
Пропал заряд в LSC и др.

### ISSUE THREAD

**Issue by MineSV** [GT-IMPACT/IMPACT-1#292]
Какую версию модпака вы используете? / Which modpack version are you using?
1.0.1.5

Вы играете в одиночке или на сервере? / Are you playing single or on a multiplayer?
одиночка

Опишите ошибку (Если нужно, приложите скриншоты). / Describe the bug (Attach screenshots if needed).
Пропали заряды во всех LSC и нарушена работа р2р грэга (пропал коннект к проводам)
![image](https://user-images.githubusercontent.com/71754209/127282602-fcb1f28d-8858-40b0-9a2f-a932610a1f78.png)

Отвязаны все трансмиттеры 
![image](https://user-images.githubusercontent.com/71754209/127283345-7a787165-af22-4ce4-99f6-16970fc2de14.png)

Визуальный баг в рецептах (возможно связан с текстурпаком от АндрейКВ)
![image](https://user-images.githubusercontent.com/71754209/127283967-152fd170-05c9-439c-950c-00e8511060ff.png)

Какие изменения вы предлагаете? / What changes do you suggest?
исправить все баги

**Comment by aagrishankov** [comment]
текстуры поменяны, про батарею написано в чанджлоге, п2п больше к проводам не цепляется

**Comment by aagrishankov** [comment]
https://github.com/GT-IMPACT/IMPACT-MODPACK/issues/294
