### ISSUE TITLE
Баг мэ?

### ISSUE THREAD

**Issue by RaitGamerGR** [GT-IMPACT/IMPACT-1#295]
Какую версию модпака вы используете? / Which modpack version are you using?
С офф сервера

Вы играете в одиночке или на сервере? / Are you playing single or on a multiplayer?
Офф сервер

Опишите ошибку (Если нужно, приложите скриншоты). / Describe the bug (Attach screenshots if needed).
Если выложить в МЭ рецепт вручную и скрафтить с шифтом, скрифтится стак и в сетку крафта не будет докладываться из мэ, если выложить через НЕИ шифтвопос, то будет докладывать без нареканий

Какие изменения вы предлагаете? / What changes do you suggest?
Пофиксить это

**Comment by RaitGamerGR** [comment]
Оно скрафтит стак, но не потратит предметы из мэ, т.е. дюпнет

**Comment by Pilad** [comment]
> Оно скрафтит стак, но не потратит предметы из мэ, т.е. дюпнет

А в одиночке?
