### ISSUE TITLE
Изменения OpenConputers и аддонов к нему

### ISSUE THREAD

**Issue by EvgenPrig** [GT-IMPACT/IMPACT-1#3]
- [x] 1. Для предмета Interweb убрать клей или добавить варианты без клея
![image](https://user-images.githubusercontent.com/70282409/91517800-55aa1f00-e8f7-11ea-8117-ddc8be56e149.png)
- [x] 2. Для предмета Charger снизить тир крафта до MV (OC микросхему до 1 тира)
![image](https://user-images.githubusercontent.com/70282409/91517948-bb96a680-e8f7-11ea-9913-de737daf0ada.png)
- [x] 3. Для предмета Disk Drive(блока) снизить тир OC микросхемы до 1 тира (иначе первый компьютер можно будет получить только с HV тира)
- [x] 4. Понизить напряжение у крафта всех планок оперативной памяти (Memory)
- [x] 5. В крафте очков и терминала для них (мод OC Glasses) понизить тир всех компонентов до второго, либо вообще до первого + См. пункт 9
- [x] 6. В крафте Geolyzer понизить тир OC микросхемы до 1, и убрать анализатор (заменить на третий сенсор например)
- [ ] ![image](https://user-images.githubusercontent.com/70282409/91518446-f4834b00-e8f8-11ea-84a7-99e9cfce137f.png)
- [ ] 7. Увеличить в конфиге заряд Наномашин, так как по умолчанию он слишком низок для использования, если возможно то убрать трату заряды при пассивном режиме работы
- [ ] 8. Добавить крафты креативным предметам (звучит страшно но по факту они не сильно отличаются от третьего тира) (кроме дебаг карты и сетевого дебагера и возможно компонент шины на 1024 компонентов)
- [x] 9. Заменить в крафте Remote Terminal апгрейд солнечной панели на например Радиоизотопный Термоэлектрический Генератор и RTG Fuel, либо же убрать апгрейд полностью, так как в очках не используется никакого источника электричества возможно и в них и в терминал добавить Linked Card (с парой для их терминалов) которая является неким квантовым тунелем в моде OC
- [x] 10. Добавить новый рецепт для Grog
![image](https://user-images.githubusercontent.com/70282409/91519392-2695ac80-e8fb-11ea-91d6-0c4c555cc883.png)
- [x] 11. Убрать в Power Distributor EV микросхему 
![image](https://user-images.githubusercontent.com/70282409/91519436-46c56b80-e8fb-11ea-80e3-aaa12c1a01b9.png)
- [x] 12. В целом понизить тир всем предметам котороые не несут никакой пользы прямой (очки, 3D принтер, голопроекторы)

**Comment by aagrishankov** [comment]
> 8. Добавить крафты креативным предметам (звучит страшно но по факту они не сильно отличаются от третьего тира) (кроме дебаг карты и сетевого дебагера и возможно компонент шины на 1024 компонентов)

Нет надобности в креативных шмотках, конфиг под грег достаточно сделан по компонентам, если нужно мы еще увеличим компоненты

**Comment by EvgenPrig** [comment]
> 
> 
> > 1. Добавить крафты креативным предметам (звучит страшно но по факту они не сильно отличаются от третьего тира) (кроме дебаг карты и сетевого дебагера и возможно компонент шины на 1024 компонентов)
> 
> Нет надобности в креативных шмотках, конфиг под грег достаточно сделан по компонентам, если нужно мы еще увеличим компоненты

Нет возможности установки карт третьего тира в Микроконтроллеры и Дронов (в частности Linked Card) что делает их намного менее полезными нежели с ней
