### ISSUE TITLE
Мультиблок принимает только один ампер.

### ISSUE THREAD

**Issue by Spartak1997** [GT-IMPACT/IMPACT-1#30]
Опишите ваше предложение
Многие игроки задают вопросы касательно мультиблоков, у которых в рецептах не указано "любое напряжение и амперы". Предлагаю убрать данные надписи вообще из неи в рецептах.

Какие проблемы решит/добавит ваше предложение?
Это избавит игрока от глупых вопросов и ошибок.

Объясните, почему ваше предложение должны реализовать?
У авторов будет меньше болеть голова, а у особо вспыльчивых личностей не будет возникать пожар.

**Comment by aagrishankov** [comment]
https://github.com/GT-IMPACT/GT5.09OFFBEAT/commit/a5e9bf2016566a4585ae6894fa02f1a293fe87f5
