### ISSUE TITLE
Назову тебя иначе

### ISSUE THREAD

**Issue by RaitGamerGR** [GT-IMPACT/IMPACT-1#301]
Опишите ваше предложение / Describe your proposal
Дать возможность форминг прессу автоматически принимать на вход любые предметы независимо от наличия рецептов с ними.

Какие проблемы решит/добавит ваше предложение? / What problems will your proposal solve / add?
Даст возможность переименовывать предметы с использованием форминг пресса в автоматическом режиме, на данный момент такая возможность есть только при ручном использовании, так как автоматически предметы туда не лезут 

Объясните, почему ваше предложение должны реализовать? / Explain why your proposal should be implemented?
так как нет другой грегофицированной автоматизируемой возможности переименовывания преметов. Инскрайбер для этого дела не подходит в связи со своей скоростью работы и спецификой приёма\выдачи предметов

**Comment by Pilad** [comment]
Ножом тыкаешь в интерфейс и можно переименовать его, ну или вроде Алексей хотел планшету это добавить вроде.

**Comment by RaitGamerGR** [comment]
Мне нужно переименовывать предметы, а не интерфейсы

> Ножом тыкаешь в интерфейс и можно переименовать его, ну или вроде Алексей хотел планшету это добавить вроде.
