### ISSUE TITLE
Fusion Casing alternate recipes are too expensive for their increased output.

### ISSUE THREAD

**Issue by dsledz** [GT-IMPACT/IMPACT-1#302]
Опишите ваше предложение / Describe your proposal
Each fusion casing has 3 recipes that increase in output and cost.
However this results in some recipes that scale poorly.

Example:
![image](https://user-images.githubusercontent.com/4691145/127876771-04f2c84d-2135-4a7a-a739-b3c049a10849.png)
vs
![image](https://user-images.githubusercontent.com/4691145/127874431-1048e15c-4592-43f1-aeef-25efee07bbef.png)
vs
![image](https://user-images.githubusercontent.com/4691145/127874460-aa0d5b55-3793-4c27-bbf6-fd20fb57d87c.png)

The field generators and circuits feel more than 3x harder than the savings on pipes, superconductors and reflectors.

The MkIII casings are worse as they start to require UEV circuits and field generators.

I'm not sure how I would modify the recipes as I don't quite understand the goals.  The higher yield recipes are blocked by later fusions already.  Are they supposed to be cheaper in raw components?  Right now they seem more expensive as field generators are expensive as they require new circuit tiers (crystal at ZPM, wetware at UV, bio at UHV).

I'm not suggesting to make casing cheaper in their base x8 recipes, I just feel like this scaling results in ignored recipes and confusion at 20 and 60 output.

If the goal is cheaper, I'd suggest keeping the field generators at the same tier but requiring twice the amount for ~3x the output.

If I'm incorrect in my resource requirements or missing something obvious, I apologize.

Какие проблемы решит/добавит ваше предложение? / What problems will your proposal solve / add?

Объясните, почему ваше предложение должны реализовать? / Explain why your proposal should be implemented?

**Comment by Spartak1997** [comment]
@dsledz So, I understand what you mean. 

Logic of those recipes is higher tier of field gen -> more output of casings. But it has some problem - UHV+ circuits. Yes, they expensive and I think it is big problem of endgame design. 

My suggestion will be redesign circuit recipes.
