### ISSUE TITLE
Reduce the number of Heavy Metal Cyclones required to feed a Hyper generator.

### ISSUE THREAD

**Issue by dsledz** [GT-IMPACT/IMPACT-1#303]
Опишите ваше предложение / Describe your proposal

Add a UEV recipe for hyperfuel III that produces at a better rate.  Maybe integrate the output from a tesseract recipe to create a feedback loop (but still limited by the production line).

I'm not in favor of just enabling parallel hatches on the heavy metal cyclone or giving it default perfect overclocking as I feel that's too powerful given how energy positive it is already.  I'm just looking for a way that doesn't involve spamming 100+ block multi-blocks.

Какие проблемы решит/добавит ваше предложение? / What problems will your proposal solve / add?

Hyperfuel III is the best source of late game power but takes 29 seconds at UHV. Overclocking the recipe results in large loss of energy.  I'm ignoring the other hyperfuel (I and II) as it seems like the light and medium enriched naquadah are better in an enriched liquid naquadah generator.

![image](https://user-images.githubusercontent.com/4691145/127879935-2cd30eb3-2152-4f9b-bef4-418c0c31c096.png)

1000L is worth around 2B EU in a hyper generator. If we ignore the energy cost of the production line before this last stage (at least ~66M/1000L non-overclocked), the standard recipe has a net of 1.75B EU.  After an overclock, it drops to 1B EU.

To run a hyper generator at full speed requires 1280L/s. Each recipe provides 69L/s (2000L every 29 seconds) so you need 19 cyclones to get 128M EU/t and it costs ~18M EU/t. So 86% efficient.

At one overclock, each cyclone gives 138L/s so only 10 are required at ~38M eu/t to get 128M eu/t. So 71% efficient.

The system is still energy positive but it feels bad needing this many cyclones for a single generator.

I've been running my hyper generator at <100% but I've also avoid upgrading some lines to UEV (or even UIV) because of this.

I haven't done the math on the issue of getting the raw components yet.  A lot of those machines already have parallel and/or perfect overclocks.

Объясните, почему ваше предложение должны реализовать? / Explain why your proposal should be implemented?

The vast number of hyperfuel III cyclones effectively limits you to one hyper generator.

**Comment by RaitGamerGR** [comment]
Закрыть, так как есть параллельность
