### ISSUE TITLE
Минутка перфекционизма или отключение уведомления обновления CodeChickenCore по умолчанию

### ISSUE THREAD

**Issue by yavarenkov** [GT-IMPACT/IMPACT-1#310]
Опишите ваше предложение / Describe your proposal
В конфиге CodeChickenCore.cfg для последующих обновлений прописать `checkUpdates=false`

Какие проблемы решит/добавит ваше предложение? / What problems will your proposal solve / add?

Убрать назойливую надпись:
![изображение](https://user-images.githubusercontent.com/60457305/128151328-435ee41d-96da-4f15-a83e-a66bc38d85eb.png)

Объясните, почему ваше предложение должны реализовать? / Explain why your proposal should be implemented?

Так красивее :D

**Comment by RaitGamerGR** [comment]
Одобряю
