### ISSUE TITLE
Отвалилась чувствительность к редстоун-сигналу на каверах

### ISSUE THREAD

**Issue by stereoseven** [GT-IMPACT/IMPACT-1#319]
Какую версию модпака вы используете? / Which modpack version are you using?
1.0.1.6

Вы играете в одиночке или на сервере? / Are you playing single or on a multiplayer?
И там и там.

Опишите ошибку (Если нужно, приложите скриншоты). / Describe the bug (Attach screenshots if needed).
Отвалилась чувствительность к редстоун-сигналу на каверах, будь то помпы, конвееры или шаттеры.
Строка Condition, игнорирует как и полагается, но при попытке установить "Condition" - просто работает, а "Invert Condition" - просто не работает, игнорируя сигнал.

Какие изменения вы предлагаете? / What changes do you suggest?
Раньше работало (скорее всего еще раньше чем 1.0.1.5), если возможно, прошу восстановите, мешает автоматизации.

**Comment by zetcool90** [comment]
вроде бы особо и не были чувствительны к редстоун сигналу, зачастую у них два положения при работе либо машина работает либо нет, кроме энерджи детектор кавера но он сам выдаёт сигнал а не принимает

**Comment by RaitGamerGR** [comment]
> Опишите ошибку (Если нужно, приложите скриншоты). / Describe the bug (Attach screenshots if needed).
> Отвалилась чувствительность к редстоун-сигналу на каверах, будь то помпы, конвееры или шаттеры.
> Строка Condition, игнорирует как и полагается, но при попытке установить "Condition" - просто работает, а "Invert Condition" - просто не работает, игнорируя сигнал.


Сделай скрин и покажи что конкретно там не работает, так не особо понятно, так как у меня такой проблемы нет и всё работает без нареканий.

**Comment by stereoseven** [comment]
Видимо я что-то перепутал...

**Comment by stereoseven** [comment]
Мое первое ишшуи, вышло комом)
