### ISSUE TITLE
Disassembler

### ISSUE THREAD

**Issue by FireWarrior2** [GT-IMPACT/IMPACT-1#320]
Опишите ваше предложение / Describe your proposal
Добавить мапу disassembler в Multi Assembling Machine или что-то сделать с такими рецептами
![2021-08-06_15 55 32](https://user-images.githubusercontent.com/18097458/128514242-d36e0980-17b0-45d4-b292-b74ad40de0f5.png)

Какие проблемы решит/добавит ваше предложение? / What problems will your proposal solve / add?
Можно будет повысить напряжение, воткнуть параллельность для снижения времени переработки

Объясните, почему ваше предложение должны реализовать? / Explain why your proposal should be implemented?

**Comment by Spartak1997** [comment]
Закрыт по причине дубликата. https://github.com/GT-IMPACT/IMPACT-MODPACK/issues/322
