### ISSUE TITLE
Эффективность важнее баланса

### ISSUE THREAD

**Issue by RaitGamerGR** [GT-IMPACT/IMPACT-1#327]
**Опишите ваше предложение / Describe your proposal**
Дать оверклокинг 4 4 хэви метал циклону и оил крекеру

**Какие проблемы решит/добавит ваше предложение? / What problems will your proposal solve / add?**
Решит проблему спама циклонами и крекерами для производства гипертоплива, космик нейтрония, инфинити каталиста,  
 крекинга нефти. т.д и т.п.

**Объясните, почему ваше предложение должны реализовать? / Explain why your proposal should be implemented?**
На данный момент разгон циклона и крекера сильно уменьшает эффективность производства топлив в первую очередь и побочных компонентов для крафтов.

**Comment by RaitGamerGR** [comment]
Проблема всё еще актуальна и хочет решения)

**Comment by aagrishankov** [comment]
Ишуя не закрыта. Обновления все равно в ближайшие 2 месяца не будет, так что и решения тоже )

**Comment by RaitGamerGR** [comment]
Просто что б она не улетела в забытые и открытые

**Comment by aagrishankov** [comment]
О того что ты написал, она не поднимется выше)

**Comment by RaitGamerGR** [comment]
Про неё вспомнят)
А может и сделают, вроде как не долго

**Comment by aagrishankov** [comment]
Если бы не долго, было бы давно сделано
