### ISSUE TITLE
Неправильно правильно имбовая формула

### ISSUE THREAD

**Issue by RaitGamerGR** [GT-IMPACT/IMPACT-1#330]
**Опишите ваше предложение / Describe your proposal**
Изменить рецепты:
Добавить на выходе ведро водорода и увеличить выход гидроксида до трёх
![image](https://user-images.githubusercontent.com/70205464/129398103-17c92368-5a38-41fb-a010-dbba53918050.png)

Уменьшить потребление натрия на входе до единицы, изменить параметры рецепта: Usage: 120eu/t, Total 40 800, Time: 17 secs(340 Ticks)
![image](https://user-images.githubusercontent.com/70205464/129398168-341d2abc-4a3f-4fed-bd08-80f16b59baf0.png)

**Какие проблемы решит/добавит ваше предложение? / What problems will your proposal solve / add?**
Решит проблему испарения натрия при зацикливании рецепта, упростит получение водорода на начальных этапах.

**Объясните, почему ваше предложение должны реализовать? / Explain why your proposal should be implemented?**
На данный момент формула неверна и рецепты требуют переработки

**Comment by stereoseven** [comment]
В первом да, добавить водород, но всё равно по молярной массе не сходится
Мне кажется правильнее было бы(как в нормальных рецептах) 
в первом случае сделать Na + 3*H2O => 3*NaOH + H; то есть слева 2 моли водорода и по одной на кислород и натрий, как и справа
а вот во втором случае по молярной всё верно. 3*NaOH => Na + H + O
Насчет достоверности тут конечно сама реакция на "реализм" не претендует, да и кислород с водородом здесь не молекулярные вещества (не O2 и H2)

**Comment by RaitGamerGR** [comment]
Не забывай, что мы оперируем не молекулами, а ведрами, так что Н2 и О2 мы опускаем. По поводу реакций немного налажал, хорошо, что ты заметил, во второй реакции изменять потребление не требуется. Но и у тебя в реакциях получается дюп натрия, ведь на выходе 3, на выходе 3 гидроксида с одного натрия, а обратно один в один

**Comment by stereoseven** [comment]
Но ведь и эти же 3 гидроксида дадут тебе 1 натрий?

**Comment by stereoseven** [comment]
Во втором 3 гидроксида а не один
(да опечатался, во втором случае имел ввиду под правильно те же 3 гидроксида на входе что и на скрине)

**Comment by stereoseven** [comment]
Вот если ты исправишь во втором случае на 1 гидроксид, а в первом воды подашь 1 ведро а на выходе опять 1 гидроксид, тогда у тебя в первом случае натрий сократится втрое, а при разложении этого гидроксида обратно умножится на 3))

**Comment by aagrishankov** [comment]
> в ребаланс химии
