### ISSUE TITLE
Дополнительная кнопка в супертанке

### ISSUE THREAD

**Issue by Dok1234** [GT-IMPACT/IMPACT-1#334]
Предлагаю добавить ещё одну кнопку в супертанк: авто-слив жидкости с условием, что танк заполнен полностью (или на 90%) 
![image](https://user-images.githubusercontent.com/72577407/130134970-4579c1d8-a432-4778-a451-90976dfe5d91.png)

Какие проблемы решит/добавит ваше предложение? / What problems will your proposal solve / add?
Это необходимо для создания постоянного запаса жидкости. Чтобы лишняя сливалась, например, в турбину, а в случае необходимости, всегда был запас в танке для ручного вычерпывания капсулами.

Объясните, почему ваше предложение должны реализовать? / Explain why your proposal should be implemented?
Потому, что не всегда надо сливать всю жижу из танка. Надо иметь запас.

**Comment by zetcool90** [comment]
перегружать лишними функциями танки не к чему, для этого в сборке есть другие средства

**Comment by Dok1234** [comment]
Зато удобно.
А каких ещё средствах говорит Зеткул? Ещё один танк с дополнительной обвязкой?
Ранее была добавлена кнопка опустошения. Она разве не лишняя? Для этого есть корзина. А то, что предлагается реально нужно.

**Comment by RaitGamerGR** [comment]
Флюид детектор позволяет это реализовать просто и без запар
