### ISSUE TITLE
Переработать неперерабатываемое 

### ISSUE THREAD

**Issue by RaitGamerGR** [GT-IMPACT/IMPACT-1#335]
**Опишите ваше предложение / Describe your proposal**
Добавить возможность разбора Tank Storage Block в дизассемблере

**Какие проблемы решит/добавит ваше предложение? / What problems will your proposal solve / add?**
Даст возможность переработки блоков со старых танков

**Объясните, почему ваше предложение должны реализовать? / Explain why your proposal should be implemented?**
Я скрафтил танк, но понял, что он мне не нужОн, а выкинуть жалко)))

**Comment by Dok1234** [comment]
Добавлю. Muffler hath всех тиров тоже прошу добавить на разборку. А ещё можно в арк добавить тоже.
