### ISSUE TITLE
Переработка алевролита (siltstone)

### ISSUE THREAD

**Issue by stereoseven** [GT-IMPACT/IMPACT-1#337]
Опишите ваше предложение? / Describe your proposal?
У siltstone dust нет применения, можно было бы добавить
Судя из википедии в основе состава - кварц, можно было бы сделать кварцит и с определенным шансом certus quartz, также в виде примесей полевой шпат (Potasium Feldspar) и глиняную пыль

Какие проблемы решит/добавит ваше предложение? / What problems will your proposal solve / add?
Добавит применение не имеющей применения пыли

Объясните, почему ваше предложение должны реализовать? / Explain why your proposal should be implemented?
У предмета есть получение, но нет применения

**Comment by aagrishankov** [comment]
>> в новую переработку руды
