### ISSUE TITLE
Кнопки в output hatch

### ISSUE THREAD

**Issue by stereoseven** [GT-IMPACT/IMPACT-1#338]
Опишите ваше предложение / Describe your proposal
Было бы неплохо добавить кнопки в output hatch, по аналогии того как это сделано в super tank'ах. Если возможно
Это кнопки функций которые настраиваются отверткой:
-заблокировать тип жидкости
-вывод предметов
-вывод жидкостей

Какие проблемы решит/добавит ваше предложение? / What problems will your proposal solve / add?
Ускорит настройку если хэтчей много и в них нужно заблокировать тип жидкости

Объясните, почему ваше предложение должны реализовать? / Explain why your proposal should be implemented?
(тут должна быть причина по которой кнопки реализовали в super tank'ах)

**Comment by Pilad** [comment]
Отвертка уже должна уметь биндить хэтч на жижи.

**Comment by RaitGamerGR** [comment]
Про лок жижи отличная идея, переключения аутпута предметов и жижи вроде как невозможно изменить, хотя звучит хорошо, одобряю.

**Comment by stereoseven** [comment]
Судя из того что пишется в консоль, там настраиваются предметы или жидкости, если будет возможно лок жидкости добавить как кнопку, то зачем оставлять остальные настройки
