### ISSUE TITLE
Нужно больше СФМа!

### ISSUE THREAD

**Issue by RaitGamerGR** [GT-IMPACT/IMPACT-1#342]
**Опишите ваше предложение / Describe your proposal**
Увеличить максимально возможное кол-во жидкости/предметов при выставлении их в командах СФМа на один знак
![image](https://user-images.githubusercontent.com/70205464/131210656-9e094b91-5a9a-4fc8-aa34-25e832c2e998.png)

**Какие проблемы решит/добавит ваше предложение? / What problems will your proposal solve / add?**
Зачастую недостатчно максимально возможного сейчас значения, так как приходится оперировать с тысячами вёдер.

**Объясните, почему ваше предложение должны реализовать? / Explain why your proposal should be implemented?**
Без данного изменения сложно оперировать большими обьёмами жидкости без дополнительных приспособ и костылей

**Comment by aagrishankov** [comment]
низя выше, надо все гуи переделывать
