### ISSUE TITLE
Не сканируется схематика для T4 ракеты

### ISSUE THREAD

**Issue by Nepoladki** [GT-IMPACT/IMPACT-1#345]
Какую версию модпака вы используете? / Which modpack version are you using?
1.0.1.6

Вы играете в одиночке или на сервере? / Are you playing single or on a multiplayer?
Одиночка

Опишите ошибку (Если нужно, приложите скриншоты). / Describe the bug (Attach screenshots if needed).
Сканер не сканирует схематику ракеты четвертого тира, пробовал в EV и IV сканерах.

Какие изменения вы предлагаете? / What changes do you suggest?
Предлагаю починить)
![image](https://user-images.githubusercontent.com/89728024/131246193-53fe8e06-1617-4407-adac-345987a2e0d5.png)

**Comment by aagrishankov** [comment]
Флешка где?

**Comment by Nepoladki** [comment]
Идиота кусок... Спасибо)
