### ISSUE TITLE
Время обработки руды в термалке

### ISSUE THREAD

**Issue by FireWarrior2** [GT-IMPACT/IMPACT-1#346]
Какую версию модпака вы используете? / Which modpack version are you using?
1.0.1.6

Вы играете в одиночке или на сервере? / Are you playing single or on a multiplayer?
одиночка

Опишите ошибку (Если нужно, приложите скриншоты). / Describe the bug (Attach screenshots if needed).
Время обработки руды в термальной центрифуге зависит от ее атомной массы (?!).
![2021-09-01_19 06 38](https://user-images.githubusercontent.com/18097458/131709053-c248d3e5-4a98-44aa-854e-f5d13f43ee01.png)

Какие изменения вы предлагаете? / What changes do you suggest?
Время должно быть фиксированным.

**Comment by aagrishankov** [comment]
>> в новую переработку руды
