### ISSUE TITLE
Exception in server tick loop

### ISSUE THREAD

**Issue by slprime** [GT-IMPACT/IMPACT-1#347]
Какую версию модпака вы используете? / Which modpack version are you using?
1.0.1.6 в CurseForge

Вы играете в одиночке или на сервере? / Are you playing single or on a multiplayer?
сингл

Опишите ошибку (Если нужно, приложите скриншоты). / Describe the bug (Attach screenshots if needed).
Исследовал энд. Не далеко от спауна. Сейчас не даёт зайти на карту. Выделил игре 12 гигов.

[crash-2021-09-03_15.52.14-server.txt](https://github.com/GT-IMPACT/IMPACT-MODPACK/files/7106020/crash-2021-09-03_15.52.14-server.txt)

**Comment by aagrishankov** [comment]
Краш понять легко, просто вылезла отрицательная координата по Y скорее всего при генерации мира, такое фиксить не хочется, так как будем удалять космомоды
