### ISSUE TITLE
Некудышные руды

### ISSUE THREAD

**Issue by RaitGamerGR** [GT-IMPACT/IMPACT-1#349]
Опишите ваше предложение / Describe your proposal
Добавить переработку молибденита и пиролюзита в доменной печи по аналогии с сфалеритом, 1 пыль + 2 кислорода = 3 слитка + SO2

Какие проблемы решит/добавит ваше предложение? / What problems will your proposal solve / add?
добавит возможность эффективной и более индустриальной переработки данных материалов,

Объясните, почему ваше предложение должны реализовать? / Explain why your proposal should be implemented?
Так как самый выггодный рецепт их переработки это просто пожарить в обычной печке 1 к 1, в электролизере же рецепт 3 к 1 +2 серы, которая бесполезна

**Comment by aagrishankov** [comment]
>> в новую переработку руды
