### ISSUE TITLE
Баг сундуков Chest Up при апгрейде

### ISSUE THREAD

**Issue by MineSV** [GT-IMPACT/IMPACT-1#35]
Какую версию модпака вы используете?
RC v2

Вы играете в одиночке или на сервере?
одиночка

Опишите ошибку (Если нужно, приложите скриншоты)
При апгрейде сундуков с помощью соответствующих chest upgrade они перестают взаимодействовать со всеми средствами коммуникаций, в частности с кондуитами Ender IO и Storage Bus.
 
Можно, конечно, просто переустановить сундук путём его сноса и установки, либо "поднять-поставить" с помощью JABBA, однако хотелось бы избегать подобный манипуляций.

Какие изменения вы предлагаете?
Исправление данного бага.

**Comment by aagrishankov** [comment]
Пытался повторить баг, не удалось, есть возможность записать видео или что то подобное?

**Comment by FireWarrior2** [comment]
Вот
https://youtu.be/3LgemnIilp8

**Comment by aagrishankov** [comment]
Ага, я так и думал что это проблема не в сундуках

**Comment by aagrishankov** [comment]
удалены апгрейды
