### ISSUE TITLE
Валики и баллончики

### ISSUE THREAD

**Issue by FireWarrior2** [GT-IMPACT/IMPACT-1#352]
Опишите ваше предложение / Describe your proposal
Сделать, чтобы валики (Painter) и баллончики (Spray Can) могли красить кабеля МЭ и красные кабеля Project Red. 
![2021-09-06_20 10 19](https://user-images.githubusercontent.com/18097458/132248410-737e91a8-50f6-47bc-84db-771df502af93.png)

Какие проблемы решит/добавит ваше предложение? / What problems will your proposal solve / add?
Окраска большого количества кабелей/проводов по месту и надобности.

Объясните, почему ваше предложение должны реализовать? / Explain why your proposal should be implemented?
Так удобнее)

**Comment by RaitGamerGR** [comment]
Тогда обратную функцию надо добавить и мэшному красителю, колор аппликатору

**Comment by aagrishankov** [comment]
Project Red не умеет красить цвета, так что эту фишку не реализовать
