### ISSUE TITLE
Мало басов!

### ISSUE THREAD

**Issue by RaitGamerGR** [GT-IMPACT/IMPACT-1#356]
Опишите ваше предложение / Describe your proposal
Добавить мультиблочному сифтеру возможность устанавливать два аутпут баса.

Какие проблемы решит/добавит ваше предложение? / What problems will your proposal solve / add?
Добавит возможность подстраховывать МЭ аутпут бас обычным и предотвратить удаление предметов при неполадках с сетью

Объясните, почему ваше предложение должны реализовать? / Explain why your proposal should be implemented?
Потому что.

**Comment by aagrishankov** [comment]
Такая схема не будет работать, МЕ аутпут в приоритете всегда выше

**Comment by RaitGamerGR** [comment]
Такая схема работает как минимум на ассемблере, было специально проверено несколько раз на сервере

**Comment by RaitGamerGR** [comment]
Мэ бас не всегда в приоритете, пэкеджер кидает сначала в обычный, хотя их строит два, если поменять местами, кидает сначала в мэ. Так что толь с приоритетами проблемы, толь с проверками

**Comment by aagrishankov** [comment]
> Такая схема работает как минимум на ассемблере, было специально проверено несколько раз на сервере

всего лишь совпадение, добавлять не буду, это будет абузится и лагать
