### ISSUE TITLE
Кабеля ОС

### ISSUE THREAD

**Issue by FireWarrior2** [GT-IMPACT/IMPACT-1#358]
Какую версию модпака вы используете? / Which modpack version are you using?
1.0.1.6

Вы играете в одиночке или на сервере? / Are you playing single or on a multiplayer?
одиночка

Опишите ошибку (Если нужно, приложите скриншоты). / Describe the bug (Attach screenshots if needed).
Не могу достать из терминала кабеля ОС. До этого достал ок. 10 штук, положил обратно, и вот. Ни с одним другим предметом подобной проблемы нет. Перезаход решил проблему.
https://youtu.be/X838a2WwkPc

Какие изменения вы предлагаете? / What changes do you suggest?
Попытаться починить кабеля

**Comment by RaitGamerGR** [comment]
Это рандомный баг, его хз даже как отловить, что б пофиксить, у меня такое возникало.

**Comment by aagrishankov** [comment]
Не воспроизводится баг, скорее всего просто клиентская ошибка была
