### ISSUE TITLE
Крафты с кузнечным молотом

### ISSUE THREAD

**Issue by TheTzdDark** [GT-IMPACT/IMPACT-1#359]
Опишите ваше предложение / Describe your proposal
Удалить все крафты с кузнечным молотом IC2
![image](https://user-images.githubusercontent.com/79448439/134569441-2183eba1-496e-4fd4-ad2d-1711e33f6698.png)

Какие проблемы решит/добавит ваше предложение? / What problems will your proposal solve / add?

Объясните, почему ваше предложение должны реализовать? / Explain why your proposal should be implemented?

**Comment by Spartak1997** [comment]
fix https://github.com/GT-IMPACT/GT5.09OFFBEAT/commit/e7f1f07959de9f8e24214331e1e1105214c404d6
