### ISSUE TITLE
Ошибка в рецепте.

### ISSUE THREAD

**Issue by Zebrix** [GT-IMPACT/IMPACT-1#36]
Какую версию модпака вы используете?
RC v2

Вы играете в одиночке или на сервере?
сервер

Опишите ошибку (Если нужно, приложите скриншоты)
Ceres glowstone dust в центрифуге - включает корявую пыльку на выходе.
![cer_gl_d](https://user-images.githubusercontent.com/26423111/96330492-cd870100-107f-11eb-8830-b409c2a0d257.PNG)

**Comment by aagrishankov** [comment]
Покажи весь рецепт плз

**Comment by Zebrix** [comment]
Эмм, так? Или как то по другому надо?
![Capture](https://user-images.githubusercontent.com/26423111/96356375-82b8c800-1117-11eb-91b3-67c0469e723d.PNG)

**Comment by aagrishankov** [comment]
да, спасибо

**Comment by Spartak1997** [comment]
Исправлено.
![image](https://user-images.githubusercontent.com/29407630/97185930-bc41a100-17b1-11eb-8265-df4062c8c40c.png)
