### ISSUE TITLE
Конфликт рецептов крэкинга в хим. реакторе

### ISSUE THREAD

**Issue by Zac666** [GT-IMPACT/IMPACT-1#363]
Какую версию модпака вы используете? / Which modpack version are you using?
1,0,1,6

Вы играете в одиночке или на сервере? / Are you playing single or on a multiplayer?
Одиночка

Опишите ошибку (Если нужно, приложите скриншоты). / Describe the bug (Attach screenshots if needed).
В хим. реакторе из Butene с микрухой №2 есть 3 рецепта, 2 из них это крекинг с ещё одной жидкостью, а третий это превращение в этилен. И последний выбирается приоритетней даже при наличии второй нужной жидкости

Какие изменения вы предлагаете? / What changes do you suggest?
Поменять микросхему для превращения в этилен

**Comment by RaitGamerGR** [comment]
Вообще убрать крекинг из многоблочных химок, для этого есть отдельный механизм.
