### ISSUE TITLE
Гт.метаайтем.нейм

### ISSUE THREAD

**Issue by RaitGamerGR** [GT-IMPACT/IMPACT-1#365]
Какую версию модпака вы используете? / Which modpack version are you using?
С офф сервера

Вы играете в одиночке или на сервере? / Are you playing single or on a multiplayer?
Офф сервер

Опишите ошибку (Если нужно, приложите скриншоты). / Describe the bug (Attach screenshots if needed).
В тултипе лапотроник суперкапаситора в билд гайде криво указаны последним 3 строки

Какие изменения вы предлагаете? / What changes do you suggest?
Исправить

**Comment by aagrishankov** [comment]
уже есть такой ишуй
