### ISSUE TITLE
При переработки Liquid Air в центрифуге на выходе отсутствует Аргон и Noble Gases

### ISSUE THREAD

**Issue by osdant** [GT-IMPACT/IMPACT-1#37]
Какую версию модпака вы используете?
Последняя релизнутая

Вы играете в одиночке или на сервере?
Сингл

Опишите ошибку (Если нужно, приложите скриншоты)
-

Какие изменения вы предлагаете?
Фиксануть по возможности

**Comment by Spartak1997** [comment]
@osdant Какая центрифуга?

**Comment by osdant** [comment]
Multiblock Centrifuge, которая без параллелей

**Comment by osdant** [comment]
В одноблочной рецепт пашет
