### ISSUE TITLE
Расширить функции гуи каверов

### ISSUE THREAD

**Issue by Dok1234** [GT-IMPACT/IMPACT-1#379]
![image](https://user-images.githubusercontent.com/72577407/142776433-28aa652a-a11c-4cb9-bf89-8978a37c7506.png)
Добавить считывание буфера, и границу, по которой выдавать сигнал

Какие проблемы решит/добавит ваше предложение? / What problems will your proposal solve / add?
 Тогда вообще никакие чипы и гейты не нужны будут.

**Comment by aagrishankov** [comment]
https://github.com/GT-IMPACT/Impact-Core/commit/069f88db0cca11d6702a703ac3fd9f677506d6f8
