### ISSUE TITLE
Крафт заборов в Assembler

### ISSUE THREAD

**Issue by LeninSaintP** [GT-IMPACT/IMPACT-1#38]
Какую версию модпака вы используете?
последняя

Вы играете в одиночке или на сервере?
Сервер

Опишите ошибку (Если нужно, приложите скриншоты)
Крафт заборов в сборщике только через дубовые доски. В то время как шейп крафт использует все виды досок.

Какие изменения вы предлагаете?
Добавить все виды досок в крафт

**Comment by Dok1234** [comment]
Дополнение к крафту забора.
В ассемблере (вариант рецепта без жиж 2доски+2палки+микруха №8) не крафтится забор. Более того, доски + микруха 8 = сундук. То есть ещё и пересечение рецептов.

**Comment by Spartak1997** [comment]
@Dok1234 мне не совсем понятно. Я не наблюдаю рецепт забора с 8 микрухой. Может вы используете старую версию пака.
