### ISSUE TITLE
HV Масс-фабрикатор работает как ЕV тир

### ISSUE THREAD

**Issue by Dok1234** [GT-IMPACT/IMPACT-1#380]
Какую версию модпака вы используете? / Which modpack version are you using?
1.0.1.6

Вы играете в одиночке или на сервере? / Are you playing single or on a multiplayer?
сервер

Опишите ошибку (Если нужно, приложите скриншоты). / Describe the bug (Attach screenshots if needed).
![image](https://user-images.githubusercontent.com/72577407/142778560-0b6497a3-eb78-4675-abc4-c92c7a849c00.png)
Этот хв мех работает как ев!

Какие изменения вы предлагаете? / What changes do you suggest?
исправить

**Comment by RaitGamerGR** [comment]
Тут нет никакой ошибки, так как низкий тир масс фабрикатора требует для своей работы большой ампераж, а так как разгоняются они 2 2, то с повышением тира их потребление постепенно выровнится и нормализуется. Более высокие их тиры будут потреблять энергии на единицу материи ровно столько же, сколько и лв.

**Comment by aagrishankov** [comment]
масс фабрикаторы на помойку :)
