### ISSUE TITLE
Жижа, колхоз и хэтчи

### ISSUE THREAD

**Issue by RaitGamerGR** [GT-IMPACT/IMPACT-1#381]
**Опишите ваше предложение / Describe your proposal**
Дать возможность ставить большее количество инпут хэтчей (в идеале 8-9) в параллельную домну.

**Какие проблемы решит/добавит ваше предложение? / What problems will your proposal solve / add?**
Даст возможность удобнее и проще автоматизировать параллельную домну по сравнению с обычной.

**Объясните, почему ваше предложение должны реализовать? / Explain why your proposal should be implemented?**
На данный момент без танцев с бубном не получится запустить её на 256 параллель с жижей.

**Comment by aagrishankov** [comment]
Уже была такая ишуя
