### ISSUE TITLE
Fluid p2p

### ISSUE THREAD

**Issue by LewisSaber** [GT-IMPACT/IMPACT-1#385]
Опишите ваше предложение / Describe your proposal
Добавить прямой рецепт создания жидких П2П в крафтинг столе путем совмещения обычного п2п и капсулы/ведра

Какие проблемы решит/добавит ваше предложение? / What problems will your proposal solve / add?
Не надо каждый раз кликать ведром или капсулой

Объясните, почему ваше предложение должны реализовать? / Explain why your proposal should be implemented?
Сократит время настроики передачи жидкости

**Comment by ranid007** [comment]
Это сложно.... Насколько помню, такое пытались сделать давненько, но все скатилось к конфликтам с NBT(ЕМНИП)

Thats.... Complicated. If i remember correctly. some time ago that thing planned to do, but due to NBT problems, thats not released.
