### ISSUE TITLE
Grek tek covers

### ISSUE THREAD

**Issue by LewisSaber** [GT-IMPACT/IMPACT-1#389]
Опишите ваше предложение / Describe your proposal
В греге существует мно;ество каверов но нигде в названии нету слова cover, моё предложения состоит в том чтоб добавить приставку cover следующим каверам:

machine controller #4978/32730
activity detector #4978/32731
fluid detector #4978/32732
item detector  #4978/32733
Energy detector #4978/32734
player detector #4978/32735

Какие проблемы решит/добавит ваше предложение? / What problems will your proposal solve / add?

все каверы можно будет легко и просто найти в неи

Объясните, почему ваше предложение должны реализовать? / Explain why your proposal should be implemented?

я постоянно использую машин котролер и флуид детектор для контроля химок и меня уже конкретно за***** постоянно искать в аешке cover, понимать что оно так не работает и ращдрадонно искать отдельно один кавер и отдельно другой

**Comment by aagrishankov** [comment]
Одобренно
