### ISSUE TITLE
Переработка нефтеносного песка

### ISSUE THREAD

**Issue by FireWarrior2** [GT-IMPACT/IMPACT-1#39]
Какую версию модпака вы используете?
1.0 rc2

Вы играете в одиночке или на сервере?
одиночка

Опишите ошибку (Если нужно, приложите скриншоты)
Отсутствует переработка пыли нефтеносного песка в большой центрифуге
![2020-10-24_00 00 14](https://user-images.githubusercontent.com/18097458/97053784-3bee2680-158c-11eb-865f-0a3e9b7107a8.png)

Какие изменения вы предлагаете?
Добавить рецепт в большую центрифугу

**Comment by Spartak1997** [comment]
Большая центрифуга просто копирует мапу обычной. Никто руками ничего не прописывал.

**Comment by FireWarrior2** [comment]
> Большая центрифуга просто копирует мапу обычной. Никто руками ничего не прописывал.

Ну, факт остается фактом, что в большой рецепта данного нет. Грег, кстати, тестовый, но вроде и в предыдущем было то же самое

**Comment by Spartak1997** [comment]
Ты проверял в самой машине?

**Comment by FireWarrior2** [comment]
Конечно, решил проверить рецепт, потому что большая центрифуга эту пыль и не перерабатывала..
