### ISSUE TITLE
Radiation proof casing и nuclear rod hatch

### ISSUE THREAD

**Issue by LewisSaber** [GT-IMPACT/IMPACT-1#395]
Какую версию модпака вы используете? / Which modpack version are you using?
1.0.1.6

Вы играете в одиночке или на сервере? / Are you playing single or on a multiplayer?
сервер

Опишите ошибку (Если нужно, приложите скриншоты). / Describe the bug (Attach screenshots if needed).
Отсутствия переработки radiation proof casing в Arc furnace
![image](https://user-images.githubusercontent.com/39595617/147415530-df906d5b-ea58-4dcd-b14f-87b0bf8f7bf9.png)
так же предлагаю добавить рецепт переработки для nuclear rod hatch,в дизасемблере или в арке
![image](https://user-images.githubusercontent.com/39595617/147415548-b3de93de-1580-4938-92df-7bf3d38bb745.png)

Какие изменения вы предлагаете? / What changes do you suggest?
добавить

**Comment by Spartak1997** [comment]
Добавил рецепт разбора для Nuclear Rod Hatch, однако так и не понял что за рецепт в арк печи для корпусов?

**Comment by RaitGamerGR** [comment]
Имел в виду добавить рецепт в арку, так как сейчас есть только для флюид экстрактора

**Comment by Spartak1997** [comment]
@RaitGamerGR ни для одного из корпусов нет рецепта в арк печке. Так зачем только одному блоку это придумывать?

**Comment by LewisSaber** [comment]
Так давайте всем добавим, корпусам от импакт мехов тоже
