### ISSUE TITLE
Crop Harvester

### ISSUE THREAD

**Issue by Zardar** [GT-IMPACT/IMPACT-1#397]
Опишите ваше предложение / Describe your proposal
Вернуть изначальную рабочую зону для Crop Harvester, либо добавить ему (либо новому аналогичному механизму) возможность выбора площади работы.

Какие проблемы решит/добавит ваше предложение? / What problems will your proposal solve / add?
Решит проблему сбора урожая быстросозревающих кропсов с высокими статами. Так же решит (за счёт снижения числа обсчитываемых кубов) проблему сбора урожая со сверхмалых полей под высокотирными ускорителями роста (word accelerator).

Объясните, почему ваше предложение должны реализовать? / Explain why your proposal should be implemented?
Огромные поля, проверяемые одним сборщиком урожая, нафиг не нужны. У любого игрока на старте эта большая площадь вызывает бурю восторга, но нет, не время улыбаться.

**Comment by aagrishankov** [comment]
Кроп харвестер и жердочки в сборке отключены в следущем обновлении.

**Comment by Pilad** [comment]
Убрать эти растения из зоны сбора - профит.
