### ISSUE TITLE
Добавить крафты ae деталей без использования ручного инструмента

### ISSUE THREAD

**Issue by Moroka** [GT-IMPACT/IMPACT-1#4]
**Опишите ваше предложение**

Добавить крафты ae деталей без использования ручного инструмента
ME Terminal
ME Storage Monitor
Illuminated Panel
ME Pattern Terminal
ME Interface Terminal
ME Crafting Terminal
ME Conversion Monitor

**Какие проблемы решит/добавит ваше предложение?**

Крафтить подобные штуки логично и научно

**Объясните, почему ваше предложение должны реализовать?**

А почему бы и нет :3

**Comment by aagrishankov** [comment]
В планах в рефакторинге концепта АЕ
