### ISSUE TITLE
Рецепт HV солярки 

### ISSUE THREAD

**Issue by FireWarrior2** [GT-IMPACT/IMPACT-1#41]
Какую версию модпака вы используете?
1.0 rc2

Вы играете в одиночке или на сервере?
одиночка

Опишите ошибку (Если нужно, приложите скриншоты)
Рецепт должен быть в 3* 3 принтере, т.к. 4* 4 - это IV тир
![2020-10-26_19 24 57](https://user-images.githubusercontent.com/18097458/97200230-ff0b7500-17c1-11eb-8c7b-73b102dfd1e5.png)

Какие изменения вы предлагаете?
Переместить рецепт в 3*3 принтер

**Comment by Spartak1997** [comment]
HV солярку перенес в принтер 3 на 3, так же как и альтернативу.
