### ISSUE TITLE
Добавить в описание Fluid Canner его вместительно.

### ISSUE THREAD

**Issue by LeninSaintP** [GT-IMPACT/IMPACT-1#42]
Опишите ваше предложение

Добавить в описание Fluid Canner его вместительно. Чтобы было видно какого тира ставить для заполнения той или иной капсулы (балона) кислорода.

Какие проблемы решит/добавит ваше предложение?

Объясните, почему ваше предложение должны реализовать?

**Comment by aagrishankov** [comment]
Давно добавил, забыл ишуе закрыть)
