### ISSUE TITLE
Избавление от оставшихся LuV+ одноблочных обработчиков

### ISSUE THREAD

**Issue by FireWarrior2** [GT-IMPACT/IMPACT-1#43]
Опишите ваше предложение
Предлагаю перенести рецепты оставшихся LuV+ одноблочных обработчиков в многоблоки.
А именно, рецепты Fluid Heater в Multi Extradification, а рецепты Polarizer в Multi Utility Machine.

Какие проблемы решит/добавит ваше предложение?
Все одноблочные обработчики после IV будут представлены в виде многоблоков.

Объясните, почему ваше предложение должны реализовать?
Данные обработчики в виде многоблоков на поздних этапах развития за счет параллельных рецептов будут очень быстро производить нужные материалы - намагничивать стержни для моторов и подогревать различные жидкости.

**Comment by aagrishankov** [comment]
https://github.com/GT-IMPACT/GT5.09OFFBEAT/commit/ab41ed3d7b885a17a5b8bdb36d8aae5ed933c5e4
https://github.com/GT-IMPACT/Impact-Core/commit/c65ee24e8e9c42b87e2eeb5ccaa79a6d28e62733
