### ISSUE TITLE
Тултип многоблоков импакта

### ISSUE THREAD

**Issue by AVVasiliev** [GT-IMPACT/IMPACT-1#434]
Какую версию модпака вы используете? / Which modpack version are you using?
1.0.1.7

Вы играете в одиночке или на сервере? / Are you playing single or on a multiplayer?
И там и там так

Опишите ошибку (Если нужно, приложите скриншоты). / Describe the bug (Attach screenshots if needed).
В описании многоблоков импакта в разделе используемых блоков не указано количество а просто пустое (at least).
![image](https://user-images.githubusercontent.com/20434719/148383031-8a47ff6b-e79c-4883-9c10-459b65267d71.png)

Какие изменения вы предлагаете? / What changes do you suggest?
Предлагаю либо добавить число необходимых блоков, либо убрать эту приписку (at least) так как сама по себе не несет смысла.

**Comment by LewisSaber** [comment]
Весь прикол импакта в том что количество структурных блоков не ограничено, а ограничено количество входов и выходов

**Comment by AVVasiliev** [comment]
Для некоторых многоблоков - вроде новой мельницы, число блоков фиксировано. Да и приписка как раз о минимально требуемом количестве. Как раз за вычетом всех хетчей

**Comment by aagrishankov** [comment]
Посчитайте и напишите, мы добавим

**Comment by AVVasiliev** [comment]
https://docs.google.com/spreadsheets/d/1FZrBT5SvVC8IYYpAX9WWwQSD1Wr_RB_fD-_Y5KxyHTw/edit?usp=sharing

Начал составлять табличку. Пока составил от парового до EV тира. Помимо информации для поля at least добавил комментарии к неточностям в тултипе у некоторых мехов

**Comment by aagrishankov** [comment]
Отлично, как доделаешь добавим сразу все, чтобы каждый многоблок был посчитан)

**Comment by RaitGamerGR** [comment]
Я уже делал подобное в отдельном канале, для некоторых машин готово

**Comment by AVVasiliev** [comment]
> Я уже делал подобное в отдельном канале, для некоторых машин готово

Поделишься ссылкой? Гляну что уже есть, чтобы не повторяться

**Comment by RaitGamerGR** [comment]
Ссылку дать не могу, но могу текст покидать в дискорд, напиши мне, подписан так же

**Comment by AVVasiliev** [comment]
Закончил табличку, вроде бы все многоблоки импакта.
https://docs.google.com/spreadsheets/d/1FZrBT5SvVC8IYYpAX9WWwQSD1Wr_RB_fD-_Y5KxyHTw/edit#gid=199104261
Там 2 страницы - на первой все многоблоки с вики на сайте, на второй все остальные которые просто через неи нашел
