### ISSUE TITLE
Multiblock Structure Hologram Projector

### ISSUE THREAD

**Issue by DiFaYaL** [GT-IMPACT/IMPACT-1#439]
Какую версию модпака вы используете? / Which modpack version are you using?
1.0.1.8

Вы играете в одиночке или на сервере? / Are you playing single or on a multiplayer?
Сервер

Опишите ошибку (Если нужно, приложите скриншоты). / Describe the bug (Attach screenshots if needed).
Крашит клиент при использовании предмета для создания голограмм
![image](https://user-images.githubusercontent.com/28961321/148577077-5d1ac3c9-aae1-4fce-aabb-c358fd5437c4.png)
![image](https://user-images.githubusercontent.com/28961321/148577198-73ccf335-d719-4c46-93f8-53453555dac7.png)

Какие изменения вы предлагаете? / What changes do you suggest?
Fix

**Comment by DiFaYaL** [comment]
[crash-2022-01-07_18.37.17-client.txt](https://github.com/GT-IMPACT/IMPACT-MODPACK/files/7830143/crash-2022-01-07_18.37.17-client.txt)

**Comment by RaitGamerGR** [comment]
Проблема уже известна и решается

**Comment by aagrishankov** [comment]
> Проблема уже известна и решается

а?
ты че то путаешь, я в первый раз вижу такой краш

**Comment by RaitGamerGR** [comment]
Сам говорил мне, что надо решить проблему когда по земле голографом тыкаешь и серв падает

**Comment by aagrishankov** [comment]
> Сам говорил мне, что надо решить проблему когда по земле голографии тыкаешь и серв падает

читай еще раз что крашится в ишуе
