### ISSUE TITLE
Долгоплавящиеся материалы

### ISSUE THREAD

**Issue by FireWarrior2** [GT-IMPACT/IMPACT-1#44]
Какую версию модпака вы используете?
1.0 rc2

Вы играете в одиночке или на сервере?
одиночка

Опишите ошибку (Если нужно, приложите скриншоты)
Автогенерируемые рецепты высокотировых материалов доменки с очень долгим временем выплавки: иттрий-барий купрат, ванадий-галлий, митрил, основа эндериума (по возможности вообще убрать рецепт, не используется), иридий, вольфрам, осмий, орихарукон.
![2020-11-02_20 16 41](https://user-images.githubusercontent.com/18097458/97898013-57092500-1d48-11eb-9871-b1b5efbfba7f.png)

Какие изменения вы предлагаете?
Сократить время выплавки, подняв расход энергии в тик.

**Comment by RaitGamerGR** [comment]
Предлагаю не изменять итоговое потребление энергии, а изменить потребление в тик и время выполнение рецепта.

**Comment by FireWarrior2** [comment]
> Предлагаю не изменять итоговое потребление энергии, а изменить потребление в тик и время выполнение рецепта.

Так я это и предложил... видимо, не совсем поняли, что такое "поднять расход энергии", подкорректирую

**Comment by RaitGamerGR** [comment]
Там не я один не понял, там и в дискорде уже спрашивали про это
