### ISSUE TITLE
Окостенелые останки

### ISSUE THREAD

**Issue by Mebilof** [GT-IMPACT/IMPACT-1#440]
Опишите ваше предложение / Describe your proposal

Вернуть шанс дропа костей

Какие проблемы решит/добавит ваше предложение? / What problems will your proposal solve / add?

Нет иных способов получения костной муки

**Comment by AVVasiliev** [comment]
Кости как дропались из породы UBC так и дропаются, не заметил отличие от того что было. Важный момент только: кости дропаются если ты копаешь молотом в обычном режиме. В адвансед они не дропаются.

**Comment by Mebilof** [comment]
Странно, видимо мне не повезло. Прилично выкопал в обычном режиме, но ни одной не дропнулось
