### ISSUE TITLE
Качественное ночное зрение.

### ISSUE THREAD

**Issue by Zebrix** [GT-IMPACT/IMPACT-1#45]
Опишите ваше предложение
Сделать работу у ночного зрения наноброни (и далее) не хуже чем в EnderIO. Слепота делает её сильно неудобной для постоянного использования.

Какие проблемы решит/добавит ваше предложение?
Освещение факелами и прочим - в топку. Ну или для архитекторов.

Объясните, почему ваше предложение должны реализовать?
Удобство.

**Comment by aagrishankov** [comment]
Ночное зрение больше не дает слепоту
