### ISSUE TITLE
IC2 шлак

### ISSUE THREAD

**Issue by LewisSaber** [GT-IMPACT/IMPACT-1#464]
Какую версию модпака вы используете? / Which modpack version are you using?

1.0.1.8
Вы играете в одиночке или на сервере? / Are you playing single or on a multiplayer?
сервер

Опишите ошибку (Если нужно, приложите скриншоты). / Describe the bug (Attach screenshots if needed).
В рецептах постоянно мигают железные и золотые пластины с ик2

Какие изменения вы предлагаете? / What changes do you suggest?
Удалить есь шлак из ик2 еквивалент которому есть в гт
В основном ето пластины, пыли и item casing

**Comment by ranid007** [comment]
Это в общем не баг, а скорее изменение рецептов. И нужно ли оно ? я к тому, что если вдруг у тебя есть ИКшные пластины их куда теперь ? Вообще жаловаться на подобые рецепты в сборках где есть ИК и Грег одновременно - дело не благодарное, как по мне.

Is it a bug ? In worth scenario its a recipe fix. Is it necessary ? Not sure/ I mean, if you get some IC plates you cant utilize them as GT one analogs ? Sounds bad, actually

**Comment by aagrishankov** [comment]
Мы не уберем это, это ордикты, автогенерируемые рецепты, а не прописанные рецепты вручную

**Comment by LewisSaber** [comment]
Я имею ввиду удалить эти предметы из игры
