### ISSUE TITLE
Жидкости в одноблочных машинках.

### ISSUE THREAD

**Issue by LeninSaintP** [GT-IMPACT/IMPACT-1#47]
Опишите ваше предложение

Сейчас одноблочные механизмы выплевывают по 1 ведру в тик. Предлагаю изменить во всех одноблочных механизмах выплевывание жидкости, сразу всей. Как это сделано в танках.

Какие проблемы решит/добавит ваше предложение?

Это не проблема, просто позволит не ждать или не вешать помпы на механизмы.

Объясните, почему ваше предложение должны реализовать?

**Comment by aagrishankov** [comment]
1) Выплевывают 1 ведро в секунду, а не в тик.
2) Думаю сделать формулу которая будет выплевывать с каждым тиром все больше за раз

Формула : 1000L/s * Тир меха

Пример: ЛВ - 1000 L/s, МВ - 2000 L/s и тд.

**Comment by aagrishankov** [comment]
https://github.com/GT-IMPACT/GT5.09OFFBEAT/commit/1058f1934a07c880640ef5b35574f03c28c1f35a
