### ISSUE TITLE
Диаграммы: баги

### ISSUE THREAD

**Issue by RaitGamerGR** [GT-IMPACT/IMPACT-1#471]
Какую версию модпака вы используете? / Which modpack version are you using?
Новейшая с доработками

Вы играете в одиночке или на сервере? / Are you playing single or on a multiplayer?
Одиночный пустой мир

Опишите ошибку (Если нужно, приложите скриншоты). / Describe the bug (Attach screenshots if needed).

**Слоты снизу не актуальны и нигде не используются. Заряды инструментов обладают слишком сомнительной полезностью.**
![image](https://user-images.githubusercontent.com/70205464/150633052-f2e743cc-4d66-4431-b063-fe74b3ef53eb.png)

**Имеются инструменты, которые невозможно сделать из некоторых материалов: Дерево, камень, все виды полимеров(поливинил, перрокс, полиэтилент, ТПФЕ, все виды резин**
![image](https://user-images.githubusercontent.com/70205464/150633119-b9f90dd6-067c-4174-9809-7c044483607a.png)

**Материалы со страниц 437 и до 452 кривые или их вообще нет**
![image](https://user-images.githubusercontent.com/70205464/150633149-63eae991-0e71-409e-815f-c03a704496fb.png)

**Адвансед Аллой имеет в материалах нулл слитки и нулл плазму**
![image](https://user-images.githubusercontent.com/70205464/150633162-ff78bf4a-f9f5-4b0d-be3f-a60287d3ac66.png)

**Comment by FireWarrior2** [comment]
Руды блоковые убрать
![2022-01-22_12 35 41](https://user-images.githubusercontent.com/18097458/150633273-257796c4-7a2a-448d-b281-3720652a61ca.png)

**Comment by FireWarrior2** [comment]
Цепочки несуществующих руд тоже бы убрать..
![2022-01-22_12 37 14](https://user-images.githubusercontent.com/18097458/150633305-f335666c-7748-41be-ae94-69e1f8a1f7a5.png)

**Comment by FireWarrior2** [comment]
У сплавов из Blast Smelter нет горячей жидкости
![2022-01-22_12 44 11](https://user-images.githubusercontent.com/18097458/150633488-1761b16e-3750-47a8-a8ab-ee236feff7d5.png)

**Comment by FireWarrior2** [comment]
Таких материалов и близко нет у нас
![2022-01-22_12 51 25](https://user-images.githubusercontent.com/18097458/150633696-1e6491a7-2621-4876-b999-e7a56a4c61c4.png)

**Comment by FireWarrior2** [comment]
Горячие слитки у материалов, которые выплавляются сразу
![2022-01-22_12 52 41](https://user-images.githubusercontent.com/18097458/150633760-e7a1bdb8-eb5b-4026-96bf-bc6655f2c64e.png)

**Comment by FireWarrior2** [comment]
У адского кварца дублируется страница (?)
![2022-01-22_12 55 33](https://user-images.githubusercontent.com/18097458/150633850-d1eb7d8e-ed7a-431c-b1d4-7872129c640f.png)
![2022-01-22_12 55 17](https://user-images.githubusercontent.com/18097458/150633852-9cf3b9cd-11f4-4dea-9750-0a8f6805d257.png)

**Comment by FireWarrior2** [comment]
Трубы высокого давления?..
![2022-01-22_12 56 38](https://user-images.githubusercontent.com/18097458/150633879-6722b3af-5616-43ee-b1a1-72b4ed8dbe99.png)

**Comment by FireWarrior2** [comment]
УХВ сверхпроводники + плазменная труба
![2022-01-22_12 57 16](https://user-images.githubusercontent.com/18097458/150633900-8c318684-b137-47ba-bd90-baee8aaa8bc0.png)

**Comment by RaitGamerGR** [comment]
В диаграмме линз эндерай, эндерперл, незерстар имеют разные применения, но располагаются в одном месте
![image](https://user-images.githubusercontent.com/70205464/150634381-492f2eee-cf7a-402f-aa57-8e421c402246.png)

**Comment by RaitGamerGR** [comment]
При просмотре квантум микросхем открывается диаграмма квантум материала

**Comment by RaitGamerGR** [comment]
Разные размеры цифр в диаграмме микрух
![image](https://user-images.githubusercontent.com/70205464/150634575-3abcd297-2d57-4b72-9822-9a6456c6662d.png)

**Comment by RaitGamerGR** [comment]
Нельзя открыть все диаграммы микросхем, открывается только вот это:
![image](https://user-images.githubusercontent.com/70205464/150634603-b0afc72c-8c0b-480a-9235-a715b8955537.png)
