### ISSUE TITLE
Диаграммы: предложения

### ISSUE THREAD

**Issue by RaitGamerGR** [GT-IMPACT/IMPACT-1#472]
По материалам:

Суперкондукторам добавить их версии с нуелвыми потерями (на данный момент отображаются отдельным материалом)
![image](https://user-images.githubusercontent.com/70205464/150633220-a7687d46-36d5-42e5-b2f9-dfb25c066969.png)
![image](https://user-images.githubusercontent.com/70205464/150633229-cc593ce5-6422-4a64-9bba-f3ac224a054b.png)

По рудам(Для дальнейшей переработки)
при клике ЛКМ по машинке на диаграмме показать её рецепт, при клике ПКМ по машинке на диаграмме, открыть все её рецепты

**Comment by RaitGamerGR** [comment]
Добавить в диаграммы новые молотки и лопатки

При клике они открывают диаграммы но самих инструментов там нет

**Comment by FireWarrior2** [comment]
Добавить катушки к материалам типа кантала
