### ISSUE TITLE
Краш + коррапт мира

### ISSUE THREAD

**Issue by Pelemesh** [GT-IMPACT/IMPACT-1#478]
Какую версию модпака вы используете? / Which modpack version are you using?
1.0.1.8

Вы играете в одиночке или на сервере? / Are you playing single or on a multiplayer?

SSP
Опишите ошибку (Если нужно, приложите скриншоты). / Describe the bug (Attach screenshots if needed).

ПКМ Yeta Wrench'om по ванильному хопперку, сломал мир, запустится смог только с бекапа.
https://paste.ee/p/ondU2
Какие изменения вы предлагаете? / What changes do you suggest?
Просто репорт краша, который не фиксится перезапуском кубача

**Comment by ranid007** [comment]
Использовались ли сторонние ресурс паки ? Из того, что я вижу, там еще что-то загорелось и оно не смогло отрисоваться / вызвало нуль. К какому блоку повернулся хоппер ? Успел заметить ? Ничего ли не бахнуло на фоне ? В общем информации мало. Из лога понятно, что крашнулась ванильная воронка и то, что сервер попытался обработать огонь, но что-то пошло не так
