### ISSUE TITLE
Drill (она же дрель)

### ISSUE THREAD

**Issue by LeninSaintP** [GT-IMPACT/IMPACT-1#48]
Опишите ваше предложение

Изменить расходование прочности у дрели на уровень LV дрели. 

Какие проблемы решит/добавит ваше предложение?

Решит проблемы дрели для 1 жилы. Для примера скафтя дрель HV с наконечником из вибрант аллой. Дрель сломалась еще до выкапывания полной жилы.

Сегодня скрафтил EV дерь. Она сломалась на 70% примерно от жилы 2х2 базальт минералов.

Объясните, почему ваше предложение должны реализовать?

Проблему надо исправлять ибо дрели в нынешнем их не имею смысла на существование. Ломаются быстро, а пересобирать их дорого. На EV тире дизассемблер имеет шанс 90%. А потерять батарейку 2к очень критично.

**Comment by aagrishankov** [comment]
https://github.com/GT-IMPACT/GT5.09OFFBEAT/commit/e71db9e8ece41f5e56743b7728b2ea17c8daa61f
