### ISSUE TITLE
Формулы у некоторых материалов

### ISSUE THREAD

**Issue by FireWarrior2** [GT-IMPACT/IMPACT-1#50]
Какую версию модпака вы используете?
1.0 rc2

Вы играете в одиночке или на сервере?
одиночка

Опишите ошибку (Если нужно, приложите скриншоты)
Отсутствуют формулы веществ у: Enderium, HSLA steel, Dark Iron, Dark Steel, Redstone Alloy, Conductive Iron, Electrical Steel, Energetic Alloy, Vibrant Alloy, Pulsating Iron, Phoenixite, Infuscolium, Orichalcum, Trinium, Mytryl и Mithril.
Отсутствуют также у Sunnarium, Soularium, но у них формулы неочевидны.
У Naquadah Alloy неправильная формула: вместо триния обозначен углерод (C).

Какие изменения вы предлагаете?
Добавить формулы этим веществам.

**Comment by aagrishankov** [comment]
https://github.com/GT-IMPACT/GT5.09OFFBEAT/commit/0bb7aad6cd69ad6baae2db9cee0b140df4eae94a
