### ISSUE TITLE
Трансформатор греет воздух

### ISSUE THREAD

**Issue by RaitGamerGR** [GT-IMPACT/IMPACT-1#503]
Какую версию модпака вы используете? / Which modpack version are you using?
Версия тест сервера

Вы играете в одиночке или на сервере? / Are you playing single or on a multiplayer?
Тест сервер

Опишите ошибку (Если нужно, приложите скриншоты). / Describe the bug (Attach screenshots if needed).
Трансформаторы имеют неадекватные потери на высоких тирах (примеры в дисе)

Какие изменения вы предлагаете? / What changes do you suggest?
Посмотреть правильность работы формулы расчёта потерь энергии у трансформаторов начиная с УВ тира

**Comment by Pilad** [comment]
Скорее они пока буффер свой наполнят кажется что потери.

**Comment by RaitGamerGR** [comment]
Нет, это именно потери. Так как после долгого простоя он всё равно выдаёт сильно меньше
