### ISSUE TITLE
Переименовывать интерфейсы можно не только через лаптоп

### ISSUE THREAD

**Issue by AndriiHalyatovskyy** [GT-IMPACT/IMPACT-1#51]
Какую версию модпака вы используете?
Тестовые моды из закрепа в дискорде

Вы играете в одиночке или на сервере?
Одиночка

Опишите ошибку (Если нужно, приложите скриншоты)
Переименовать интерфейс можно так же с помощью этих чипов (redstone gold chipset, engraved gold chip и тд).
![1](https://user-images.githubusercontent.com/39647846/98448020-e4c28700-2131-11eb-8c60-3599d3442a73.PNG)

Какие изменения вы предлагаете?
Убрать эту возможность

**Comment by aagrishankov** [comment]
https://github.com/GT-IMPACT/Applied-Energistics-2-Unofficial/commit/6f8878eaac1f7e08aaacf640ad58e0b86d2c9be2
