### ISSUE TITLE
Oilsands vein contains Aluminium Ore

### ISSUE THREAD

**Issue by schliip** [GT-IMPACT/IMPACT-1#55]
Какую версию модпака вы используете?
1.0rc2

Вы играете в одиночке или на сервере?
solo

Опишите ошибку (Если нужно, приложите скриншоты)
Oilsands vein contains Aluminium Ore
![image](https://user-images.githubusercontent.com/34576051/98454799-6e745380-2136-11eb-9092-238ff95cc929.png)

Какие изменения вы предлагаете?
Replace Aluminium Ore > Oilsands Ore

**Comment by Spartak1997** [comment]
@schliip it's correct vein. We deleted bauxite vein in Overworld and it's reason why we changed oilsand

**Comment by schliip** [comment]
Understood
