### ISSUE TITLE
Убрать старые кольца для доменки

### ISSUE THREAD

**Issue by Dok1234** [GT-IMPACT/IMPACT-1#56]
Опишите ваше предложение
![image](https://user-images.githubusercontent.com/72577407/98478007-616f6700-21ff-11eb-95ff-c94b935db145.png)

Предлагаю убрать старые кольца
Старые давно уже не нужны.

**Comment by aagrishankov** [comment]
https://github.com/GT-IMPACT/GT5.09OFFBEAT/commit/344a369926b713bf66573f303f9e6481dcb8fadc
