### ISSUE TITLE
У Fluid Import bus из AE2FC нет рецепта

### ISSUE THREAD

**Issue by FireWarrior2** [GT-IMPACT/IMPACT-1#565]
Какую версию модпака вы используете? / Which modpack version are you using?
1.0.2.2

Вы играете в одиночке или на сервере? / Are you playing single or on a multiplayer?
одиночка

Опишите ошибку (Если нужно, приложите скриншоты). / Describe the bug (Attach screenshots if needed).
![2023-02-02_21 42 24](https://user-images.githubusercontent.com/18097458/216420119-3f820af5-318b-4a98-a353-f6504ca43626.png)

Какие изменения вы предлагаете? / What changes do you suggest?
Добавить рецепт.

**Comment by Pilad** [comment]
Исправил https://github.com/GT-IMPACT/impactRecipesModule/pull/5

**Comment by Pilad** [comment]
![изображение](https://user-images.githubusercontent.com/9840821/216434935-6d31acd6-378f-4fe9-adb1-634add4e1797.png)
