### ISSUE TITLE
Убрать сообщения о новых версиях модов

### ISSUE THREAD

**Issue by FireWarrior2** [GT-IMPACT/IMPACT-1#566]
Опишите ваше предложение / Describe your proposal
Убрать сообщение о новых версиях модов при старте мира.
![2023-02-01_23 38 35](https://user-images.githubusercontent.com/18097458/216420456-6d9bf54e-28ed-4f49-8ded-0de518b1d47a.png)

Какие проблемы решит/добавит ваше предложение? / What problems will your proposal solve / add?
Очистка чата от ненужной информации.

Объясните, почему ваше предложение должны реализовать? / Explain why your proposal should be implemented?
Зачем эти сообщения игроку?

**Comment by Pilad** [comment]
Добавил.
