### ISSUE TITLE
Защита от радиации нано- и квантовой брони

### ISSUE THREAD

**Issue by FireWarrior2** [GT-IMPACT/IMPACT-1#58]
Опишите ваше предложение
Нано- и квантовая броня (в т.ч. гравик и k2p4) должна защищать от радиоактивных предметов.

Какие проблемы решит/добавит ваше предложение?
Не придется переодеваться в резиновый костюм, теряя защиту, быстрый бег и т.п. Также не позволит игроку умереть от случайно схваченной радиоактивной гадости.

Объясните, почему ваше предложение должны реализовать?
Для удобства.

**Comment by aagrishankov** [comment]
https://github.com/GT-IMPACT/Impact-Core/commit/5127f4274c8d9263af77ae82d838e669f1e2269a
