### ISSUE TITLE
Переписать генератор на антиматерии

### ISSUE THREAD

**Issue by LeninSaintP** [GT-IMPACT/IMPACT-1#589]
Опишите ваше предложение / Describe your proposal

Переписать рецепт генератора на антиматерии и его компонентов, чтобы он был доступен на позднем LUV раннем ZPM. 

Какие проблемы решит/добавит ваше предложение? / What problems will your proposal solve / add?

Сделает его полезным. А сейчас он делает после ГиперГена

Объясните, почему ваше предложение должны реализовать? / Explain why your proposal should be implemented?

После нерфа реакторов, он будет являться хорошей альтернативой.

**Comment by FireWarrior2** [comment]
Заменить в скане ув плазма генератор на зпм.
Заменить в рецепте генератора сверхпроводники ухв на зпм.
Минимальный тир хетчей в структуре - зпм.
Заменить в рецепте контейнера с антиматерией нейтроний на дюраний/тританий, материю - на naquadria liquid.

Опционально - добавить возможность перегонять еще некоторые жидкости в плазму, про скорость подумать:
- гелий в гелиевую;
- кислород в кислородную;
- аргон в аргоновую.
