### ISSUE TITLE
Ребаланс SOFC генераторов v.2

### ISSUE THREAD

**Issue by CronyXD** [GT-IMPACT/IMPACT-1#596]
Опишите ваше предложение / Describe your proposal

_**РЕБАЛАНС Т1 SOFC:**_
Скорость нагрева увеличить с 0,4%/s до 1%/s
Прямой выход ЕУ увеличить с 2048 eu/t до 4096 eu/t
Потребление кислорода снизить с 400L/s до 112L/s
Потребление газов увеличить в 2 раза. Пример - очищенный газ, с 320L/s до 640L/s.
Выработку обычного пара увеличить с 18к L/s до 54к L/s

_**ПОЧЕМУ ИМЕННО ЭТИ ЦИФРЫ?**_ 
Значения связаны между собой соблюдением КПД выработки пара не выше 50% от прямого выхода и соотношениями вода:обычный пар - 1:160, а вода:гретый пар - 1:80.

Допустим прямой выход 2048 eu/t, выход пара должен составить ~50% от этого значения.
Возьмем средний турбинный ротор из вибранта. Он принимает 36к L/s пара и имеет эффективность 115%
36 000/40*1,15=1035eu/t. Узнаем потребление кислорода, используя греговскую формулу разложения воды на водород и кислород (3л воды = 2л водорода и 1л кислорода). 36 000/160/3=75L/s.

Это значение подходит по условиям, но нужно учитывать растущее потребление энергии на ЕВ тире, и общая генерация в 3к eu/t не является ни конкурентной, ни достаточной для удовлетворения энергетических потребностей на данном тире.

Взяв за основу прямой выход в 4096eu/t, большой турбинный ротор из вибранта, принимающий 54к L/s пара с эффективностью 140%, получатся следующие значения:
Потребление кислорода = 54 000/160/3 = 112L/s;
Выход пара = 54 000/40*1,4 = 1890 eu/t; 
Общая генерация = 4 096+1 890 = 5 986 eu/t. 
Результат соответствует условиям и является достойной альтернативой дизельным генераторам мк1 и газовым турбинам.

_**РЕБАЛАНС Т2 SOFC:**_
Скорость нагрева увеличить с 0,4%/s до 1%/s
Прямой выход ЕУ увеличить с 8 192 eu/t до 16 384 eu/t
Потребление кислорода снизить с 1 200L/s до 450L/s
Потребление газов увеличить в 2 раза. Пример - очищенный газ, с 1 280L/s до 2 560L/s.
Выработку гретого пара увеличить с 36к L/s до 108к L/s

_**ПОЧЕМУ ИМЕННО ЭТИ ЦИФРЫ?**_ 
Расчеты аналогичны Т1, за исключением расчета гретого пара. Соотношение вода:пар здесь взято 1:80, т.к. гретый пар в 2 раза энергоплотнее обычного пара. Соответственно потребление кислорода = 108 000/80/3 = 450L/s
2 паровых турбины для гретого пара с большими вибрантовыми роторами принимают по 54кL/s, их выход составит:
108 000/20*1,4 = 3 780*2 eu/t + выход обычного пара с обеих турбин, равный 54кL/s. (54 000/40*1,4 = 1 890 eu/t)
Общая генерация Т2 SOFC = 16 384 + 3780*2 + 1890 = 25 834 eu/t.
Итог: генерация T2 SOFC при её полной реализации подобна дизельному генератору МК2 в буст режиме.

_**РЕБАЛАНС Т3 SOFC:**_
Скорость нагрева увеличить с 0,4%/s до 1%/s
Прямой выход ЕУ увеличить с 32 768 eu/t до 49 152 eu/t (можно безопасно ставить 2 4А ИВ динамо)
Потребление кислорода оставить 2 000L/s
Потребление газов увеличить в 1,5 раза. Пример - очищенный газ, с 5 120L/s до 7 680L/s.
Выработку гретого пара увеличить с 72к L/s до 480к L/s (Пар подается в Huge Turbine)

_**ПОЧЕМУ ИМЕННО ЭТИ ЦИФРЫ?**_ 
В отличие от Т1 и Т2, увеличение прямого выхода Т3 лишь в 1,5 раза связано с расположением T3 SOFC по генерации между Т2 и Т3 ЯРами. **_Далее следует небольшое отступление о ядерных реакторах._**

Пояснение: учитывается бафф генерации пара реакторов в 2-3 раза, т.к. на данный момент она составляет 
21,6к - 28,8к eu/t для Т2 и 105к - 140к eu/t для Т3 (зависит от вида MOX стержней). 

Предположим, что реакторы имеют генерацию ~60k eu/t (Т2) и ~280k eu/t (Т3) с урановыми MOX стержнями.
Рассчитав общую генерацию T3 SOFC, получим 49 152 + 24 000 = 73 152 eu/t.

Соблюдена очередность доступности генераторов по мощностям:
1. Т2 ЯР становится доступным после освоения орбиты, постройки ME Provider и 3D Printer 4x4 
2. Т3 SOFC доступен после сбора AssLine, т.к. требует LuV моторы в крафте электролитов
3. Т3 ЯР доступен при наличии калифорния, AssLine и LuV схем

Какие проблемы решит/добавит ваше предложение? / What problems will your proposal solve / add?
1. SOFC станут полезными. 
2. Уберет спам газовыми турбинами, тк начиная с ЕВ тира количество потребителей стремительно увеличивается, что требует соответствующей генерации, которую указанные генераторы в малом количестве не способны предоставить.
3. Добавит интересный альтернативный вариант использования газов, актуальный до позднего ИВ тира.

Объясните, почему ваше предложение должны реализовать? / Explain why your proposal should be implemented?
1. Является простым решением проблемы энергетического баланса для ЕВ и ИВ тиров.
2. Добавит разнообразия при выборе способа генерации энергии.

**Comment by Pilad** [comment]
Поток газа рассчитывается от его калорийности, множитель всему топливу поднимет расход.

**Comment by Pilad** [comment]
Т1 по задумке выдает только обычный пар. Ещё вопрос в Динамо, на 4к по-моему нет двухамперников, а четырех амперники начинаются вроде с 8кв.

**Comment by CronyXD** [comment]
Я указал, что расход всех видов газа будет увеличен. Очищенный как пример написал. 
Т1 и выдает обычный пар, я ничего не менял здесь.
4К можно снимать с помощью 2А ЕВ динамо.
