### ISSUE TITLE
В незере нет подземных источников жидкости

### ISSUE THREAD

**Issue by LokiGT** [GT-IMPACT/IMPACT-1#6]
Какую версию модпака вы используете?
1.0RC

Вы играете в одиночке или на сервере?
single

Опишите ошибку (Если нужно, приложите скриншоты)
В незере не создаются подземные источники жидкости, хотя в конфиге они прописаны.

Какие изменения вы предлагаете?

**Comment by LokiGT** [comment]
проверил на 1.0RC2 и снова везде есть кроме незера...

**Comment by FireWarrior2** [comment]
Да, в незере нет
Баг не пофиксили
