### ISSUE TITLE
LV Pump

### ISSUE THREAD

**Issue by LeninSaintP** [GT-IMPACT/IMPACT-1#60]
Какую версию модпака вы используете?

Препатчевую.

Вы играете в одиночке или на сервере?

Сервер

Опишите ошибку (Если нужно, приложите скриншоты)

Забагался крафт LV Pump, есть 2 вида рецетов. В одном используеться 2 болта но не используются провода. Второй стандартный. Но его не хочет использовать Component Assembler 
![2020-11-13_00 53 31](https://user-images.githubusercontent.com/73186487/99000924-1204a000-254b-11eb-9329-d2fae53b21a5.png)

Какие изменения вы предлагаете?

Починить квест

**Comment by Spartak1997** [comment]
Уже исправлено! https://github.com/GT-IMPACT/Impact-Core/compare/eef1187ad58e...c3f189d94f25
