### ISSUE TITLE
Убрать потребление в пол-ампера и чуть меньше

### ISSUE THREAD

**Issue by FireWarrior2** [GT-IMPACT/IMPACT-1#601]
Опишите ваше предложение / Describe your proposal
Предлагаю изменить энергопотребление в рецептах, потребляющих пол-ампера или чуть меньше (например, 4096 еу/т) в меньшую или большую сторону.
![2023-11-30_15 08 55](https://github.com/GT-IMPACT/IMPACT-MODPACK/assets/18097458/bc695802-804e-46af-9a55-2dcb2b1781d8)
![2023-11-30_15 09 23](https://github.com/GT-IMPACT/IMPACT-MODPACK/assets/18097458/91521f41-60e0-4a53-95ae-97da3749d797)
![2023-11-30_15 09 33](https://github.com/GT-IMPACT/IMPACT-MODPACK/assets/18097458/e2cd5fe2-3897-46ef-91be-079dc6d3da0a)

Какие проблемы решит/добавит ваше предложение? / What problems will your proposal solve / add?
Если сделать везде меньше половины (например, 3950 еу/т), то потери не так сильно будут влиять при установке двухамперного хетча, но останется непонятный для многих разгон (с потреблением 4096 еу/т и iv energy hatch рецепт может разогнаться до 16384 еу/т). 
Если сделать больше половины, то подобные рецепты вообще не смогут так разгоняться.

Объясните, почему ваше предложение должны реализовать? / Explain why your proposal should be implemented?
Убрать неочевидный разгон, из-за которого возникают проблемы, или снизить потери при таком разгоне.

**Comment by Pilad** [comment]
Наоборот идет разгон, если рецепт МВ 64 еу. С хэтчем на 128 на 2 амперы он попробует разогнаться. А если сделать 96 еу, то разгона не будет.

**Comment by FireWarrior2** [comment]
Ну, я и предлагаю либо снизить потребление (например, до 48), чтобы потери при разгоне не так сильно влияли, либо увеличить потребление (например, до 96), чтоб вообще не разгонялось.

**Comment by Spartak1997** [comment]
Я думаю можно закрыть обсуждение. В принципе основной массив исправлен. Если еще обнаружите, отпишитесь.
