### ISSUE TITLE
Проверить баг с генераторами и мультихэтчами

### ISSUE THREAD

**Issue by aagrishankov** [GT-IMPACT/IMPACT-1#603]
**Какую версию модпака вы используете? / Which modpack version are you using?**
1.0.2.2-

**Вы играете в одиночке или на сервере? / Are you playing single or on a multiplayer?**
single + multiplayer

**Опишите ошибку (Если нужно, приложите скриншоты). / Describe the bug (Attach screenshots if needed).**
Жижа чекается как к потреблению, но по факту используется другая жижа

**Какие изменения вы предлагаете? / What changes do you suggest?**
фикс

**Comment by FireWarrior2** [comment]
Есть такое..
![2023-12-15_19 11 06](https://github.com/GT-IMPACT/IMPACT-MODPACK/assets/18097458/cd57bcfe-ab29-49de-ab9a-89419260eca8)
![2023-12-15_19 11 13](https://github.com/GT-IMPACT/IMPACT-MODPACK/assets/18097458/f6221796-e4d9-44e1-b91d-c8e687a29386)
