### ISSUE TITLE
Добавить тир ракет.

### ISSUE THREAD

**Issue by LeninSaintP** [GT-IMPACT/IMPACT-1#61]
Опишите ваше предложение

В окне НЕИ, где показываются планеты, на которых можно найти руды. Добавить тир ракет для удобного понимания, когда мне будет доступна планета.

Какие проблемы решит/добавит ваше предложение?

Простота поиска места добычи руды.

Объясните, почему ваше предложение должны реализовать?

Оно клевое :D

**Comment by EvgenPrig** [comment]
Удваиваю

**Comment by aagrishankov** [comment]
https://github.com/GT-IMPACT/Impact-Core/commit/f0f4441cc56b5fbd3844325a9d1766453d8240c8
