### ISSUE TITLE
Кривая проверка структуры Тессеракта

### ISSUE THREAD

**Issue by FireWarrior2** [GT-IMPACT/IMPACT-1#611]
Какую версию модпака вы используете? / Which modpack version are you using?
1.0.2.2

Вы играете в одиночке или на сервере? / Are you playing single or on a multiplayer?
одиночка

Опишите ошибку (Если нужно, приложите скриншоты). / Describe the bug (Attach screenshots if needed).
У тессеракта весьма кривая проверка структуры: если убрать energy hatch по бокам и поставить их снова, то многоблок не соберется, и лишь поворот/переустановка контроллера заставит его это сделать.
![2023-12-15_18 49 34](https://github.com/GT-IMPACT/IMPACT-MODPACK/assets/18097458/63c58a7f-1f07-4088-b853-be9fc61a99f6)

Какие изменения вы предлагаете? / What changes do you suggest?
Исправить проверку структуры.

**Comment by Pilad** [comment]
Контроллер всегда стоит ставить в последнюю очередь. Бластуха так же чудила помню. если кольца меняешь, то не собиралась. Приходилось например один блок кольца над контроллером снимать и обратно ставить.После блок апдэйта её и отпускало.

**Comment by FireWarrior2** [comment]
Особенности структуры
