### ISSUE TITLE
Отсутствуют рецепты некоторых предметов AE2

### ISSUE THREAD

**Issue by EvgenPrig** [GT-IMPACT/IMPACT-1#62]
Какую версию модпака вы используете?
IMPACT 1.0 RC2

Вы играете в одиночке или на сервере?
Сервер

Опишите ошибку (Если нужно, приложите скриншоты)
Нет рецепта у ME Wireless Access Point и Crafting Monitor
![image](https://user-images.githubusercontent.com/70282409/99151748-49d82880-26ae-11eb-8912-de1939dc02b2.png)
![image](https://user-images.githubusercontent.com/70282409/99151755-5197cd00-26ae-11eb-85ac-bc2f7a9b0435.png)

Какие изменения вы предлагаете?
Добавить рецепт и проверить не пошло что нибудь еще не так, именно рецев нет только у этих двух предметов, возможно у других они могли изменится но при беглом осмотре ничего такого не было замечено

**Comment by aagrishankov** [comment]
Поинт уже пофиксили, остался только монитор)
