### ISSUE TITLE
Шины из ExtraCells2 перестали опозноваться OpenComputers как me_exportbus

### ISSUE THREAD

**Issue by EvgenPrig** [GT-IMPACT/IMPACT-1#63]
Какую версию модпака вы используете?
IMPACT 1.0 RC2

Вы играете в одиночке или на сервере?
Сервер

Опишите ошибку (Если нужно, приложите скриншоты)
Шины из ExtraCells2 перестали опозноваться OpenComputers как me_exportbus(вследствии чего невозможно ими пользоваться через компьютер), теперь они aemultipart у которого из функционала только просмотр статистики сети

Какие изменения вы предлагаете?
Узнайте родителей этих шин
Узнайте эти шины
Перевернуть там всё вверх дном
Но наказать эти шины

**Comment by aagrishankov** [comment]
Обновить ОС нужно
