### ISSUE TITLE
Неправильный заряд паяльника с energium кристаллом

### ISSUE THREAD

**Issue by FireWarrior2** [GT-IMPACT/IMPACT-1#634]
Какую версию модпака вы используете? / Which modpack version are you using?
1.1.0 dev

Вы играете в одиночке или на сервере? / Are you playing single or on a multiplayer?
одиночка

Опишите ошибку (Если нужно, приложите скриншоты). / Describe the bug (Attach screenshots if needed).
У паяльника со Small Energium Crystal неправильный заряд - 3,2 млн еу.
![2024-01-08_20 13 40](https://github.com/GT-IMPACT/IMPACT-MODPACK/assets/18097458/9fafc862-7947-4c83-8f09-03359ff63faf)

Какие изменения вы предлагаете? / What changes do you suggest?
Уменьшить заряд до 400 тыс еу.

**Comment by Pilad** [comment]
https://github.com/GT-IMPACT/GT5.09OFFBEAT/pull/34
