### ISSUE TITLE
Производство PBI

### ISSUE THREAD

**Issue by FireWarrior2** [GT-IMPACT/IMPACT-1#65]
Опишите ваше предложение
Предлагаю некоторые изменения и улучшения в производственную цепочку PBI:
1) Если возможно (Computronics??) изменить рецепт диоксида хрома: 1 хром + 2 ведра кислорода, вместо 5 ведер
2) Добавить в БХР рецепт производства триоксида хрома в 1 этап (1 хром + 3 ведра кислорода)
3) Добавить в цетрифугу рецепт Селитра -> Нитрат калия (подобно Стеклянная пыль -> Диоксид кремния)

Какие проблемы решит/добавит ваше предложение?
1) Нормальные коэффициенты у рецепта.
2) В одноблочном химреакторе триоксид хрома будет производиться в 2 этапа, а в БХР - в 1.
3) Эту соль не придется искуственно делать, если она есть в виде минерала.

Объясните, почему ваше предложение должны реализовать?
Для удобства и порядка)

**Comment by Spartak1997** [comment]
Done https://github.com/GT-IMPACT/GT5.09OFFBEAT/commit/3ddfb10f80ca4da6304ee3056a9497273856aebc
