### ISSUE TITLE
Steve's addon suggestion

### ISSUE THREAD

**Issue by 0lafe** [GT-IMPACT/IMPACT-1#66]
Steve's addon is a mod for steves factory manager. It allows you to label blocks, copy manager code, and lots of other useful features. Generally makes SFM more usable on complex/large setups. Also has some performance bonuses to it.

If it is added, you do need to disable the energistics connector block. It's broken, and can cause item dupes if the craft is allowed. Removing a recipe is fine, it just can't be craftable.

**Comment by aagrishankov** [comment]
Already downloaded :)

**Comment by Spartak1997** [comment]
@0lafe Done https://github.com/GT-IMPACT/Impact-Core/commit/c87ed9cefd0996127f0e28855ccdd487c61fcb2e
