### ISSUE TITLE
Красители GregTech

### ISSUE THREAD

**Issue by Nuck-Nuck** [GT-IMPACT/IMPACT-1#67]
Опишите ваше предложение
Добавить для всех красителей грега OreDictionary Name.

Какие проблемы решит/добавит ваше предложение?
Возможность использования в рецептах, т.к. на данный момент у них нет применения.

Объясните, почему ваше предложение должны реализовать?
Унификация различных красителей в греговский вариант и удобство их хранения.

![2020-11-19_22 59 58](https://user-images.githubusercontent.com/45174204/99691345-b773c280-2abb-11eb-9d38-456711f54a73.png)

**Comment by Spartak1997** [comment]
Done https://github.com/GT-IMPACT/GT5.09OFFBEAT/commit/663dcf5026535cbed740841faf2f7dac0756dfd7
