### ISSUE TITLE
SFM request

### ISSUE THREAD

**Issue by 0lafe** [GT-IMPACT/IMPACT-1#68]
If you don't want to do this, go ahead and close the ticket, it might be difficult or annoying.

My suggestion is it would be nice if Steve's had a way to detect all fluids. It does it for items, you can set it to "match all" and it will detect any instance of an item. However we don't have one for fluids, you need to list every fluid which is way too many. 

If you do want to do this, I think it would be in here 

https://github.com/GTNewHorizons/Steve-s-Factory-Manager/blob/master/src/main/java/vswe/stevesfactory/components/ComponentMenuLiquidCondition.java

**Comment by aagrishankov** [comment]
I don't quite understand what this is about
