### ISSUE TITLE
Не убирать кропы

### ISSUE THREAD

**Issue by nartallax** [GT-IMPACT/IMPACT-1#7]
Опишите ваше предложение
Не убирать большую часть кропов из модпака.

Какие проблемы решит/добавит ваше предложение?
Кропы - это контент. Кропы - это стиль жизни. Многим игрокам кропы нравятся. Если их не убирать, модпак не пострадает.

Объясните, почему ваше предложение должны реализовать?
Кропы не являются такой уж имбой, какой их видят некоторые.
1. Через них нельзя бесконечно получать сколько-нибудь серьезные ресурсы. Самое клевое, что с их помощью можно получать бесконечно - алюминий. Титан, вольфрам и более поздние ресурсы с помощью кропов бесконечно получать затруднительно (можно через материю, но это более-менее лейтгеймово).
2. Чтобы получить хороший полноценный огород, нужно потратить минимум дня три-четыре реального времени, а также достичь определенного уровня развития. Кропы с плохими статами сажать малополезно; для получения хороших статов у кропов нужно их длительное время селекционировать; даже с наличием хороших инструментов (portable scanner) выведение базового кропа с хорошими статами займет день-два.
И даже после получения полноценного огорода необходима какая-никакая инфраструктура для переработки его плодов в материалы - в виде постоянного источника энергии, а также логистики для доставки плодов к месту переработки.
3. Для выращивания более-менее продвинутых кропов (на уран, вольфрам и т.д.) нужны блоки руды этих материалов. Т.о. кропы не избавляют от необходимости добывать руду.

В итоге, как мне кажется, кропы не сильно более имбовы, чем те же пчелы, которых планируется оставить.

**Comment by aagrishankov** [comment]
Пчел тоже не планируем оставлять*

**Comment by nartallax** [comment]
Мысль: можно ужесточить "прихотливость" кропов.
Насколько я понимаю механику кропов, у них есть некоторая условная "прихотливость". Хай-тир кропы, которые растут в недостаточно хороших для них условиях, умирают.
Предложение: добавить многоблок, улучшающий условия выращиваемых внутри него кропов + увеличить прихотливость всех кропов. Чтобы все более-менее интересные кропы можно было выращивать только внутри многоблока, потому что без него они все умирают.
Недостаток: если этот многоблок будет требовать энергии, то одно проседание убьет все кропы. Не уверен, как с этим вообще лучше поступить.

**Comment by Spartak1997** [comment]
1. Кропсы и пчелы будут убраны по причине изменения переработки руд. Концептуально они не впишутся.
2. Вы только что подтвердили, что кропсы бесполезны. Тогда зачем их защищать?
3. Сборка не предполагает пустую трату времени, так что исходя из этой логики данный "контент" лишь отнимает игровой тайминг игрока.
4. Удаление позволит в значительной степени очистить Грег от ненужных классов, что значительно оптимизирует сборку.

**Comment by aagrishankov** [comment]
@Spartak1997 4 причем тут очистить грег? все кропы в 1 классе сидят

**Comment by Spartak1997** [comment]
Про кропсы в курсе. Но ты чекни пчел, там любая помойка. Можешь по истории глянуть.

**Comment by Zebrix** [comment]
Хм, я бы вообще подумал насчет - не выпилить ли forestry с концами? Древоферма запилена в греге, необходимости в старой не вижу.
Кропсы оставить только для еды или дерева, ну или там красителей. Никакого умножения руд с них не надо.

**Comment by nartallax** [comment]
> Вы только что подтвердили, что кропсы бесполезны. Тогда зачем их защищать?  

Нет, они не бесполезны. Они просто позволяют не дрочиться со всякими мелочами жизни, вида "черт, опять кончилось олово на крафт микрух, надо идти копать".
> Сборка не предполагает пустую трату времени  

Давайте тогда сборка при запуске будет удалять майнкрафт, ведь он тоже, по сути своей, пустая трата времени.
Как именно ты определяешь, что пустая трата времени, а что - нет? Игрушки предназначены для того, чтобы получать от них удовольствие, и если какой-то контент это удовольствие дает - почему бы и нет?
> Удаление позволит в значительной степени очистить Грег от ненужных классов, что значительно оптимизирует сборку  

А вот подтверждение этому мне хотелось бы видеть в числах.
Да, классов может быть много. Где именно будет профит от их удаления? В весе файлов? В скорости загрузки? В ускорении обсчета тика? И каково это ускорение/уменьшение будет, в числах?

**Comment by Spartak1997** [comment]
Ваш пример слишком маловероятен начиная с лв тира. Тинкер инструменты, майнеры.

И я вновь повторюсь, дублирование материалов не подходит нашей сборке. Слишком уж посредственно выглядит по сравнению с промышленными агрегатами.

**Comment by nartallax** [comment]
> Ваш пример слишком маловероятен начиная с лв тира. Тинкер инструменты, майнеры.  

Что тинкер инструменты и майнеры? Они за меня пойдут что-то копать?
Я вообще не хочу задумываться о том, что у меня может кончиться что-то из базовых ресурсов. Иметь их бесконечно, после недели построения грядок и селекции - божественно приятно.
Вообще вот тебе более полнвесный пример - я хочу иметь многоблоки без поломок. Для этого нужно скрафтить автомейтенанас хатч и накормить его всякими детальками для починки. Для полностью автоматического крафта деталек (и ХВ микрух в частности) нужны разнообразные ресурсы, которые может предоставить огород.
И я с радостью принимаю эту цепочку и иду пилить огород и автокрафт, потому что не ломающиеся многоблоки - это очень хорошо, я обожаю самоподдерживающиеся бесконечные системы. Потому что мне нравится сама идея.
А ты это хочешь сломать. Ну чьорт же пабери.

> дублирование материалов не подходит нашей сборке  

Вот эту мысль вообще не понял. Что где кого дублирует?
Возможно, для понимания этого мне нужно посмотреть на новую версию модпака, чего я пока не сделал. Ладно.

**Comment by aagrishankov** [comment]
Сборку двигаем к реализму, никаких ресурсов из воздуха не существует, я соглашусь оставить и переделать кропсы, но если они никак не будут тем, чем сейчас являются. А именно, ресурсы из воздуха. Допустим чтобы растения умирали за 1-2 цикла работы

**Comment by LokiGT** [comment]
хотелось бы иметь возможность через конфиг их включать. я лично не вижу проблем ни в кропсах ни пчелах, в большей степени играю в одиночную игру и тема имбаланса меня не волнует.

**Comment by aagrishankov** [comment]
Ишуе закрываем, как время придет до кропсов, дадим знать
