### ISSUE TITLE
Непромываемое

### ISSUE THREAD

**Issue by FireWarrior2** [GT-IMPACT/IMPACT-1#70]
Какую версию модпака вы используете?
1.0 rc2

Вы играете в одиночке или на сервере?
Одиночка

Опишите ошибку (Если нужно, приложите скриншоты)
На всякий случай напишу еще сюда.
Данные материалы не промываются в Dust Washer:
Vermiculite
Alunite
Plutonium 241
Osmirinigon
Silicon
Andradite
Naqlatigon
Pitchblende
Forcicium
Kyanite
Pollucite
Mithril
Electrotine
Dolomite
Wollastonite
Trona
Uvarovite
Perlite
Sheldonite
Kaolinite
Zeolite
Fullers earth
Glauconite sand
Basaltic mineral sand
Granitic mineral sand
Gypsum
Tungsten
Garnet sand
Asbestos

Какие изменения вы предлагаете?
Они должны там промываться

**Comment by aagrishankov** [comment]
Крч мне это надоело, я просто включу ордикты и отключу в неи мапу

**Comment by aagrishankov** [comment]
https://github.com/GT-IMPACT/GT5.09OFFBEAT/commit/cef83eb237b1129849f41d792a176254f03cbae5
