### ISSUE TITLE
AE2 

### ISSUE THREAD

**Issue by Foreno1** [GT-IMPACT/IMPACT-1#71]
Какую версию модпака вы используете?
**1.0 RC2**

Вы играете в одиночке или на сервере?
**Одиночный режим**

Опишите ошибку (Если нужно, приложите скриншоты)
**Отсутствуют крафты шариков с краской необходимые для аппликатора цвета**
![bandicam 2020-11-24 21-59-19-323](https://user-images.githubusercontent.com/69816909/100127650-2593fd00-2ea1-11eb-880b-a55417f7cb99.jpg)

**Comment by Spartak1997** [comment]
Fixed
https://github.com/GT-IMPACT/Impact-Core/commit/cbd46198c956d96bf5f6a6c79c57fcf511b078fc
