### ISSUE TITLE
Tinkers Construct Recipe

### ISSUE THREAD

**Issue by DiFaYaL** [GT-IMPACT/IMPACT-1#75]
Опишите ваше предложение
Пересмотреть крафт брони путешественника(Traveller's).

Какие проблемы решит/добавит ваше предложение?
Станет востребованной.

Объясните, почему ваше предложение должны реализовать?
Она сейчас не рентабельна.

**Comment by Spartak1997** [comment]
Done https://github.com/GT-IMPACT/Impact-Core/commit/3699d0c76de2d1fb096dde4e32334cba3ac6ef46
