### ISSUE TITLE
Pyrolyse Oven Casing

### ISSUE THREAD

**Issue by DiFaYaL** [GT-IMPACT/IMPACT-1#79]
Опишите ваше предложение
Удалить блок "Pyrolyse Oven Casing"
https://prnt.sc/vw29ja

Какие проблемы решит/добавит ваше предложение?
Не будет заводить в заблуждение новичков.

Объясните, почему ваше предложение должны реализовать?
Данный блок негде не используется.

**Comment by aagrishankov** [comment]
Сделаем)
