### ISSUE TITLE
Степассист для всех!

### ISSUE THREAD

**Issue by RaitGamerGR** [GT-IMPACT/IMPACT-1#81]
**Опишите ваше предложение**
Добавить квантовым и наноботинкам степассист(возможность автоматического подъема на 1 блок)

**Какие проблемы решит/добавит ваше предложение?**
Увеличит полезность данных тапок при ходьбе пешком 

**Объясните, почему ваше предложение должны реализовать?**
Такая очень полезная фича увеличит полезность броней ХВ+ тира относительно дешевой брони путешественника с такой функцией

**Comment by aagrishankov** [comment]
done
