### ISSUE TITLE
Редстоун аллой провода

### ISSUE THREAD

**Issue by RaitGamerGR** [GT-IMPACT/IMPACT-1#82]
**Какую версию модпака вы используете?**
Последнюю?

**Вы играете в одиночке или на сервере?**
Сервер ZonaSumraka

**Опишите ошибку (Если нужно, приложите скриншоты)**
Нет рецепта производства редстоун аллой проводов в ваермилле, только в экструдере

**Какие изменения вы предлагаете?**
Добавить рецепт в ваермилл
![image](https://user-images.githubusercontent.com/70205464/102017941-ef002280-3d7a-11eb-80a5-9bf737067ac7.png)
![image](https://user-images.githubusercontent.com/70205464/102017949-0ccd8780-3d7b-11eb-8808-52eb4dec9ea0.png)

**Comment by Spartak1997** [comment]
Fixed https://github.com/GT-IMPACT/GT5.09OFFBEAT/commit/c0faf1d0163f69aa885bcf4157fe5429b8ef1985
