### ISSUE TITLE
Получение бутадиена

### ISSUE THREAD

**Issue by FireWarrior2** [GT-IMPACT/IMPACT-1#83]
Какую версию модпака вы используете?
1.0 rc2

Вы играете в одиночке или на сервере?
одиночка

Опишите ошибку (Если нужно, приложите скриншоты)
Лишний рецепт производства бутадиена из бутена на МВ. Нужно оставить только ЕВ.
![2020-12-12_11 17 55](https://user-images.githubusercontent.com/18097458/102024258-174f4780-3da2-11eb-9acd-99de9237b137.png)
![2020-12-12_11 17 59](https://user-images.githubusercontent.com/18097458/102024262-18807480-3da2-11eb-8a65-3610a3e5d178.png)

Какие изменения вы предлагаете?
Убрать рецепт на МВ. Также должен получаться побочкой водород (C4H8->C4H6+H2)

**Comment by Spartak1997** [comment]
Fixed https://github.com/GT-IMPACT/GT5.09OFFBEAT/commit/1038ace2b33958719b491cce6648dc14d843ba0e
