### ISSUE TITLE
Рецепты для модулей GalaxySpace

### ISSUE THREAD

**Issue by FireWarrior2** [GT-IMPACT/IMPACT-1#84]
Опишите ваше предложение
Предлагаю добавить рецепты предметам из GalaxySpace Module "Stabilization" и Module "Expander". 
![2020-12-16_16 59 15](https://user-images.githubusercontent.com/18097458/102358024-1136b200-3fc0-11eb-8b96-3045b95eb381.png)
![2020-12-16_16 59 23](https://user-images.githubusercontent.com/18097458/102358031-1267df00-3fc0-11eb-8566-94577b85343c.png)

Какие проблемы решит/добавит ваше предложение?
Первый модуль стабилизирует атм. давление, установленный в Gravity Module.
Второй расширяет радиус действия Magnetic Field Generator.

Объясните, почему ваше предложение должны реализовать?
Возможно, данным модулям просто забыли дать рецепт. Для механизмов, для которых они предназначены, они будут полезны.

**Comment by Spartak1997** [comment]
Done https://github.com/GT-IMPACT/Impact-Core/commit/cd0507b590863b8294167cf0bec5a201b15fc99b
