### ISSUE TITLE
Ошибки рудогенерации и генерации жидкостей

### ISSUE THREAD

**Issue by FireWarrior2** [GT-IMPACT/IMPACT-1#86]
Какую версию модпака вы используете?
1.0.0.0

Вы играете в одиночке или на сервере?
одиночка

Опишите ошибку (Если нужно, приложите скриншоты)
Титан: нет руд
Европа: генерируются кастомные руды
Тритон: слишком мало руд генерируется
Ни на одной планете нет новых жидкостей, остались старые

Какие изменения вы предлагаете?
Фиксить..

**Comment by aagrishankov** [comment]
Пока принято решение отключить титан, европа и тритон плюс/минус пофикшены, жидкости тоже пофикшены
