### ISSUE TITLE
Формулы у некоторых материалов #2

### ISSUE THREAD

**Issue by FireWarrior2** [GT-IMPACT/IMPACT-1#88]
Какую версию модпака вы используете?
1.0.0.0

Вы играете в одиночке или на сервере?
одиночка

Опишите ошибку (Если нужно, приложите скриншоты)
Необходимо исправить формулы у: Quantum, Pikonium64B, EnderEye, Vibrant Alloy, Pulsating Iron, Mytryl или Draconium (Dr или D), Superconductor Base UEV, UHV, UV, ZPM. Они имеют либо "?", либо "Empty".
![2020-12-16_18 43 28](https://user-images.githubusercontent.com/18097458/102410190-4283a200-4001-11eb-8527-5146c192f08e.png)

Какие изменения вы предлагаете?
Исправить формулы.

**Comment by aagrishankov** [comment]
Где "?" это уже слишком длинные формулы, они не влезают, а "Empty" пофикшу

**Comment by FireWarrior2** [comment]
![2021-01-03_20 34 11](https://user-images.githubusercontent.com/18097458/103484874-19d21980-4e03-11eb-9f82-2253dc2797e5.png)
Исправить на черную сталь
Enderium.mChemicalFormula="("+EnderiumBase.mChemicalFormula+")\u2082("+DarkSteel.mChemicalFormula+")("+Enderpearl.mChemicalFormula+")";

**Comment by aagrishankov** [comment]
Будет включено в рефакторинг материалов
