### ISSUE TITLE
Pulsating Crystal

### ISSUE THREAD

**Issue by FireWarrior2** [GT-IMPACT/IMPACT-1#90]
Какую версию модпака вы используете?
1.0.0.0

Вы играете в одиночке или на сервере?
одиночка

Опишите ошибку (Если нужно, приложите скриншоты)
Потерялся рецепт пульсирующего кристалла, который нужен для пространственного приемопередатчика.
![2020-12-17_01 09 26](https://user-images.githubusercontent.com/18097458/102412576-b6737980-4004-11eb-9598-6194692ef30b.png)

Какие изменения вы предлагаете?
Добавить рецепт или заменить кристалл на что-то более индустриальное.

**Comment by Spartak1997** [comment]
Fixed https://github.com/GT-IMPACT/Impact-Core/compare/51e1d7d4b5f0...02487199831f
