### ISSUE TITLE
Рецепт сплава алюминиевой латуни в Alloy Smelter

### ISSUE THREAD

**Issue by Romtonika** [GT-IMPACT/IMPACT-1#92]
Отсутствует рецепт алюминиевой латуни в печке сплавов.
![javaw_LRAWjD5hMs](https://user-images.githubusercontent.com/57370156/102560695-ea719c00-40e3-11eb-81c6-fa9193b1de7a.png)

**Comment by Spartak1997** [comment]
Done https://github.com/GT-IMPACT/Impact-Core/compare/6323b700c214...791918a687d8
