### ISSUE TITLE
После обновления исчезли некоторые жидкостные интерфейсы.

### ISSUE THREAD

**Issue by MineSV** [GT-IMPACT/IMPACT-1#99]
Какую версию модпака вы используете?
1.0.0.1

Вы играете в одиночке или на сервере?
одиночка

Опишите ошибку (Если нужно, приложите скриншоты)
![2020-12-19_12 18 42](https://user-images.githubusercontent.com/71754209/102683723-e1242480-41f4-11eb-8fe6-b0cdcb447a00.png)
![2020-12-19_12 19 00](https://user-images.githubusercontent.com/71754209/102683726-e2ede800-41f4-11eb-9029-aa414af50c34.png)
При первом заходе в мир, после обновления, исчезли некоторые жидкостные интерфейсы.
Какие изменения вы предлагаете?
Исправить этот баг.

**Comment by aagrishankov** [comment]
Это не исправить, такой код ец
